---
title: "Prepare_CIRAD_trees"
author: "Vincyane"
date: "`r Sys.Date()`"
output: html_document
---
**25 ha - les 9ha**

# Packages
```{r Setup, include = F}
library(tidyverse)
library(data.table)
library(readr)
library(sf)
library(TreeData)

# remotes::install_github("EcoFoG/EcoFoG", build_vignettes = F)
# library(EcoFoG)
```

```{r, include = F}
# read_csv("~/PhD/Inventories/Data/Adults/Paracou16_2020.csv")

AdultsP16 <- read_csv("~/PhD/Inventories/Data/Adults/Paracou/2023-09-29_ParacouP16AllYears.csv") %>% # all P16 (25 ha)
  filter(CensusYear == 2020) %>% # last year
  filter(!SubPlot %in% c(13,14,15,18,19,20,23,24,25)) # remove ALT zone
  # Only alive trees
  filter(CodeAlive == T) %>%
  # Scientific name
  unite(col = "ScientificName", c("Genus", "Species"),
        sep = "_", na.rm = TRUE, remove = F) %>% 
  # idTree as character
  mutate(idTree = as.character(idTree)) %>% 
  # Circ to DBH
  mutate(Diameter = CircCorr/pi) %>%  # 12489
  mutate(Xutm = round(Xutm, 1)) %>%
  mutate(Yutm = round(Yutm, 1))


# AdultsPP <- read_csv("~/PhD/Inventories/Data/Adults/NouraguesPetitPlateau_2022.csv")
```

# Env data
```{r}
TopoLevels <- st_read("D:/Mes Donnees/PhD/SIG_data/Topo_P16_4classes/Topo4Levels.shp") %>% 
  filter(Plot==16) %>% mutate(TopoTypeEn = ifelse(idTopo ==38, "Lower slope", TopoTypeEn))

P16 <- st_as_sf(raster::shapefile("D:/Mes Donnees/PhD/SIG_data/Plots Paracou/OverallPlots.shp")) %>% 
  filter(Plot == "16") %>% 
  st_set_crs(st_crs(TopoLevels))
```

# Trees in pinotière ?
```{r, eval = F}
AdultsP16_plot <- AdultsP16 %>% 
  filter(VernName != "pinot") %>% 
  filter(Family != "Arecaceae") %>% 
  filter(!is.na(Xutm)) %>% 
  filter(!is.na(Yutm)) %>% 
  st_as_sf(coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(TopoLevels))

ggplot() +
  geom_sf(data = TopoLevels, aes(fill = TopoTypeEn)) +
  geom_sf(data = AdultsP16_plot, size = 0.1) + # , aes(col= Genus)
  scale_fill_manual(values = c("Plateau" = "#009E73",
                               "Slope"= "#E7B800",
                               "Lower slope"= "#bfe6eb", 
                               "Bottomland" = "#1f78b4")) +
  theme_classic() +
  labs(fill= "Topography")
```

```{r, eval = F}
adults_BF <- st_intersection(AdultsP16_plot, TopoLevels[TopoLevels$TopoTypeEn == "Bottomland",]) # en BF
adults_BF <- st_intersection(adults_BF, P16[P16$Subplot %in% c("11","12","16","17","21","22"),]) # pinotière


ggplot() +
  geom_sf(data = TopoLevels, aes(fill = TopoTypeEn)) +
  geom_sf(data = adults_BF, size = 1, aes(col= Genus)) + # , aes(col= Genus)
  geom_sf(data = sf::st_cast(P16, "LINESTRING")) +
  scale_fill_manual(values = c("Plateau" = "#009E73",
                               "Slope"= "#E7B800",
                               "Lower slope"= "#bfe6eb", 
                               "Bottomland" = "#1f78b4")) +
  theme_classic() +
  guides(fill = FALSE) +
  labs(fill= "Topography")

unique(adults_BF$ScientificName) # 137 sp dans la pinotière hors palmiers
```

```{r}
adults_BF <- AdultsP16 %>% 
  filter(!is.na(Xutm)) %>% 
  filter(!is.na(Yutm)) %>% 
  st_as_sf(coords = c("Xutm", "Yutm")) %>% 
  st_set_crs(st_crs(TopoLevels)) %>% 
  st_intersection(TopoLevels[TopoLevels$TopoTypeEn == "Bottomland",]) %>%  # en BF
  st_intersection(P16[P16$Subplot %in% c("11","12","16","17","21","22"),]) # pinotière

AdultsP16 <- AdultsP16 %>% 
  filter(!idTree %in% adults_BF$idTree) # remove pinotière trees

ggplot() +
  geom_sf(data = TopoLevels, aes(fill = TopoTypeEn)) +
  geom_sf(data = AdultsP16 %>%
            st_as_sf(coords = c("Xutm", "Yutm")) %>%
            st_set_crs(st_crs(TopoLevels)), size = 0.1) + # , aes(col= Genus)
  scale_fill_manual(values = c("Plateau" = "#009E73",
                               "Slope"= "#E7B800",
                               "Lower slope"= "#bfe6eb", 
                               "Bottomland" = "#1f78b4")) +
  theme_classic() +
  labs(fill= "Topography")
```

# Apply taper correction if measured HOM
```{r}
# use "Diameter" and "HOM" columns to create -> "TaperDBH_TreeDataCor"
# POMCertainty = 0: deduced ; 1: measured

cortrees <- AdultsP16 %>% # 12489
  filter(POMCertainty == 1) %>%
  mutate(HOM = POM/100) %>% # in m
  TaperCorrection(
    DefaultHOM = 1.3,
    
    TaperParameter = function(DAB, HOM) 0.156 - 0.023 * log(DAB) - 0.021 * log(HOM),
    TaperFormula = function(DAB, HOM, TaperParameter, DefaultHOM) DAB / (exp(- TaperParameter*(HOM - DefaultHOM))),
    
    DetectOnly = F
  ) %>% 
  rename(DBHcorTaper = TaperDBH_TreeDataCor) # 12213

range(cortrees$Diameter - cortrees$DBHcor) # -4.31897  0.00000 cm DBH

AdultsP16 <- AdultsP16 %>% 
  filter(POMCertainty!=1) %>% 
  mutate(DBHcorTaper = Diameter) %>% 
  mutate(DiameterCorrectionMeth = "") %>% 
  mutate(HOM_TreeDataCor = POM/100) %>% 
  bind_rows(cortrees) # 12489
```

# Detect multistems and manage them
```{r}
# multistems <- AdultsP16 %>% 
#   select(Xutm,Yutm, ScientificName, idTree) %>%
#   group_by(Xutm,Yutm) %>%
#   mutate(index = row_number()) %>% 
#   pivot_wider(names_from = index, values_from = idTree) %>% 
#   filter(!is.na(`2`)) %>%  # 98 multistem trees
#   unite(col = "Coord", c("Xutm", "Yutm"),
#         sep = "_", na.rm = TRUE, remove = F)
# 
# AdultsP16 %>%
#   filter(Xutm==285249.3 & Yutm ==581289.8) %>% 
#   select(Xutm,Yutm, idTree, ScientificName, VernName, CensusYear, Circ, Diameter)


source("~/PhD/R_codes/PhD/Inventory_scripts/Functions/DetectMultistem.R")
AdultsP16 <- DetectMultistem(AdultsP16)
```

```{r}
multistems <- AdultsP16 %>% 
  filter(grepl("Multistem potential", Comment)) %>% # seulement les dupliqués
  mutate(BasalArea = pi*(DBHcorTaper/2)^2) %>% 
  group_by(Coord) %>% 
  arrange(desc(DBHcorTaper)) %>% 
  mutate(Stem.nb = 1:n()) %>% # numérote les stems par ordre décroissant de DBH
  mutate(BasalAreacor = sum(BasalArea)) %>% # somme des surfaces terrières
  mutate(DBHcor = 2*sqrt(BasalAreacor/pi)) %>% 
  arrange(desc(DBHcor)) %>% 
  ungroup() %>% 
  mutate(Multistem = T)

AdultsP16 <- AdultsP16 %>% 
  filter(!grepl("Multistem potential", Comment)) %>% # supprimer les dupliqués
  mutate(Multistem = F) %>% 
  mutate(Stem.nb = 1) %>%
  mutate(DBHcor = DBHcorTaper) %>%
  bind_rows(multistems)
```

```{r}
# On ALT zone
multistems %>% 
  filter(SubPlot %in% c(13,14,15,18,19,20,23,24,25)) # only 1 tree with 2 stems, not botanically identified
```
# Subspecies
```{r}
unique(AdultsP16$ScientificName) # _subsp.

test <- AdultsP16 %>%
  filter(grepl("_subsp", ScientificName))
unique(test$ScientificName)
# "Protium_opacum_subsp.rabelianum" , "Micropholis_guyanensis_subsp.duckeana", "Zanthoxylum_acuminatum_subsp.juniperinum"

```

# Check missing bota
```{r}
test <- AdultsP16 %>%
  filter(is.na(ScientificName) |
           grepl("indet", ScientificName) |
           grepl("Indet", ScientificName) |
           grepl("aceae", ScientificName) |
           # grepl("_sp", ScientificName) & grepl("\\.", ScientificName) | 
           grepl("_aff", ScientificName) & grepl("\\.", ScientificName) |
           grepl("_cf_", ScientificName)) # 1881, 2046 avec les sp.

unique(test$ScientificName)
```

# My filters
**faudra que ce soit le mmemes espèces que celles choisies dans ALT**
```{r}
AdultsP16_filtred <- AdultsP16 %>%
  # Only spatialised trees
  filter(!is.na(Xutm) & !is.na(Yutm)) %>% # # aucun
  # Only the principal stem
  filter(Stem.nb == 1) %>%
  filter(DBHcor>=10) %>% # enlève 7 tiges
  # Only alive trees
  # filter(CodeAlive == T) %>% # déjà fait avant
  
  # Only measured trees
  filter(!is.na(DBHcor)) %>% # aucun
  
  # Only botanical identified
  filter(!is.na(ScientificName)) %>%
  filter(!grepl("indet", ScientificName)) %>%
  filter(!grepl("Indet", ScientificName)) %>%
  filter(!grepl("aceae", ScientificName)) %>%
  # filter(!(grepl("_sp", ScientificName) & grepl("\\.", ScientificName))) %>% # On garde sp.chiffre ?
  filter(!(grepl("_aff", ScientificName) & grepl("\\.", ScientificName))) %>%
  filter(!grepl("_cf_", ScientificName)) %>%
  mutate(ScientificName_c = sub("\\_subsp.*", "", ScientificName)) %>%
  mutate(SubSpecies = ifelse(grepl("_subsp", ScientificName), sub(".*_subsp.", "", ScientificName), NA)) %>%
  rename(ScientificName_old = ScientificName,
         ScientificName = ScientificName_c) %>% 
  
  # Count individuals by species
  group_by(ScientificName) %>% 
  mutate(N = n()) %>% 
  ungroup() %>% # 10602
  # Take only sp >= 30 ind
  filter(N >= 30) # enlève 1887 tiges
# 8294
```

```{r}
nrow(AdultsP16) - nrow(AdultsP16_filtred) # 4267
length(unique(AdultsP16$ScientificName)) - length(unique(AdultsP16_filtred$ScientificName)) # 401 species lost, 66 sp kept

write.csv(AdultsP16_filtred, "D:/Mes Donnees/PhD/Inventories/Data/Adults/Paracou/AdultsP16_filtred.csv")
```

```{r}
Species <- as.data.frame(unique(AdultsP16_filtred$ScientificName))

write.csv(Species, "D:/Mes Donnees/PhD/Inventories/Data/Adults/Paracou/AdultsP16_species_filtred.csv")
```

