---
title: "Light ontogenic niche relative to the community"
author: "Vincyane Badouard"
date: "`r Sys.Date()`"
output: pdf_document
---

# Packages
```{r Setup, include = F}
library(tidyverse)
library(data.table)
library(ggforce)
library(sf)
library(raster)
library(terra)
library(tidyterra)

Path = "//amap-data.cirad.fr/work/users/VincyaneBadouard/Inventories/Explo_plots"
# "D:/Mes Donnees/PhD/R_codes/PhD/Inventory_scripts/Exploration/pdf"

sp <- (read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,3]) # 75

```

# Import cleaned inventory data
```{r}
# load real Presence-absences data on 25ha 
load("D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha.Rdata")
# View(datalist[[1]])

datalist <- datalist[names(datalist) %in% sp] # only species in sp

```

# Check abundances in each bin
```{r abondances, eval =F}
plist <- vector('list', length(sp))

for(p in 1:length(sp)){
  plist[[p]] <- local({
    # p = 24
    dataS <- datalist[names(datalist) %in% sp[p]][[sp[p]]] # %>% 
    # mutate(logDBH = round(logDBH, digits = 1)) %>% 
    # mutate(logTransmittance = round(logTransmittance, digits = 0)) 
    
    
    if(all(is.na(dataS[dataS$Presence==1,]$Strategy))){cl = "black"
    }else if(unique(na.omit(dataS[dataS$Presence==1,]$Strategy))=="Canopy species"){cl = "#E7B800"
    }else if(unique(na.omit(dataS[dataS$Presence==1,]$Strategy=="Understory species"))){cl = "#009E73"}
    
    dataS %>% 
      # loged bins
      mutate(log_dbh_bin = cut_interval(log(DBHcor), n = 5), # n = number of intervals to create
             log_trans_bin = cut_interval(log(Transmittance), n = 10)) %>% 
      group_by(log_dbh_bin, log_trans_bin) %>% 
      summarise(n = n()) %>% 
      # mutate(Presence = recode(as.character(Presence),
      #                          "1" = "Presence", "0" = "Absence")) %>% 
      # pivot_wider(names_from = Presence, values_from = n) %>% 
      # mutate_at(vars(c("Absence", "Presence")), ~ ifelse(is.na(.), 0, .)) %>% 
      # mutate(freq = Presence/(Presence+Absence)) %>% # ratio Presence/total
      ungroup() %>% 
      # the labels debinned:
      mutate_at(vars(c("log_dbh_bin", "log_trans_bin")),
                ~gsub(c("\\[|]|\\(|)"), "", .)) %>% 
      separate(log_dbh_bin, c("log_dbh_bin_l", "log_dbh_bin_h"),
               sep = ",", convert = TRUE) %>% 
      separate(log_trans_bin, c("log_trans_bin_l", "log_trans_bin_h"),
               sep = ",", convert = TRUE) %>% 
      rowwise() %>% 
      mutate(log_dbh = mean(c(log_dbh_bin_l, log_dbh_bin_h)),
             log_trans = mean(c(log_trans_bin_l, log_trans_bin_h))) %>% 
      select(log_dbh, log_trans, n) %>% 
      
      ggplot(aes(log_dbh, log_trans, fill = n)) +
      theme_minimal() +
      geom_raster() +
      geom_vline(xintercept = log(10)) + # 10 cm DBH
      scale_fill_viridis_c("Individuals number", trans = "log10") +
      scale_x_continuous("Diameter at Breast Height (DBH, cm)",
                         n.breaks = 10, labels = ~round(exp(.),2)) + # delog
      scale_y_continuous("Light Transmittance (%)",
                         n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
      theme(plot.title = element_text(colour = cl)) +
      labs(title = sp[p])
  })
}

plots <- gridExtra::marrangeGrob(plist, nrow = 2, ncol = 2)
# plots

```

# Environment bins
```{r}
plist <- vector('list', length(sp))

for(p in 1:length(sp)){
  plist[[p]] <- local({
    # p = 33
    dataS <- datalist[names(datalist) %in% sp[p]][[sp[p]]]
    
    
    if(all(is.na(dataS[dataS$Presence==1,]$Strategy))){cl = "black"
    }else if(unique(na.omit(dataS[dataS$Presence==1,]$Strategy))=="Canopy species"){cl = "#E7B800"
    }else if(unique(na.omit(dataS[dataS$Presence==1,]$Strategy=="Understory species"))){cl = "#009E73"}
    
    N <- nrow(dataS[dataS$Presence==1,])
    
    dataS %>% 
      # loged bins
      mutate(log_dbh_bin = cut_interval(log(DBHcor), n = 5), # n = number of intervals to create
             log_trans_bin = cut_interval(log(Transmittance), n = 10)) %>% 
      group_by(Presence, log_dbh_bin, log_trans_bin) %>% 
      summarise(n = n()) %>% 
      mutate(Presence = recode(as.character(Presence),
                               "1" = "Presence", "0" = "Absence")) %>% 
      pivot_wider(names_from = Presence, values_from = n) %>% 
      mutate_at(vars(c("Absence", "Presence")), ~ ifelse(is.na(.), 0, .)) %>% 
      mutate(freq = Presence/(Presence+Absence)) %>% # ratio Presence/total
      ungroup() %>% 
      # the labels debinned:
      mutate_at(vars(c("log_dbh_bin", "log_trans_bin")),
                ~gsub(c("\\[|]|\\(|)"), "", .)) %>% 
      separate(log_dbh_bin, c("log_dbh_bin_l", "log_dbh_bin_h"),
               sep = ",", convert = TRUE) %>% 
      separate(log_trans_bin, c("log_trans_bin_l", "log_trans_bin_h"),
               sep = ",", convert = TRUE) %>% 
      rowwise() %>% 
      mutate(log_dbh = mean(c(log_dbh_bin_l, log_dbh_bin_h)),
             log_trans = mean(c(log_trans_bin_l, log_trans_bin_h))) %>% 
      select(log_dbh, log_trans, freq) %>% 
      
      ggplot(aes(log_dbh, log_trans, fill = freq*100)) +
      theme_minimal() +
      geom_raster() +
      geom_vline(xintercept = log(10)) + # 10 cm DBH
      scale_fill_viridis_c("Species\nFrequency\n(%)") +
      scale_x_continuous("Diameter at Breast Height (DBH, cm)",
                         n.breaks = 10, labels = ~round(exp(.),2)) + # delog
      scale_y_continuous("Light Transmittance (%)",
                         n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
      theme(plot.title = element_text(colour = cl)) +
      labs(title = paste(sp[p], " (N: ",N,")", sep=""))
  })
}

plots <- gridExtra::marrangeGrob(plist, nrow = 2, ncol = 2)
# plots

ggsave("Light_onto_niche_relativetothe_community.pdf",
       path = "//amap-data.cirad.fr/work/users/VincyaneBadouard/Inventories/Explo_plots",
       plots, width = 15, height = 10)
```

# Boxplots
```{r, eval = F}
plist <- vector('list', length(sp))

for(p in 1:length(sp)){
  plist[[p]] <- local({
    # p = 33
    dataS <- datalist[names(datalist) %in% sp[p]][[sp[p]]]
    
    
    if(all(is.na(dataS[dataS$Presence==1,]$Strategy))){cl = "black"
    }else if(unique(na.omit(dataS[dataS$Presence==1,]$Strategy))=="Canopy species"){cl = "#E7B800"
    }else if(unique(na.omit(dataS[dataS$Presence==1,]$Strategy=="Understory species"))){cl = "#009E73"}
    
    N <- nrow(dataS[dataS$Presence==1,])
    
    dataS %>% 
      # loged bins
      mutate(log_dbh_bin = cut_interval(logDBH, n = 5)) %>%  # n = number of intervals to create
      # log_trans_bin = cut_interval(logTransmittance, n = 10)) %>% 
      # group_by(Presence, log_dbh_bin, log_trans_bin) %>% 
      # summarise(logTransmittance_mean = mean(logTransmittance),
      #           Sd = sd(logTransmittance)) %>% 
      mutate(Presence = recode(as.character(Presence),
                               "1" = "Presence", "0" = "Absence")) %>% 
      ungroup() %>% 
      # the labels debinned:
      mutate_at(vars(c("log_dbh_bin")),
                ~gsub(c("\\[|]|\\(|)"), "", .)) %>% 
      separate(log_dbh_bin, c("log_dbh_bin_l", "log_dbh_bin_h"),
               sep = ",", convert = T) %>% 
      rowwise() %>% 
      mutate_at(vars(c("log_dbh_bin_l", "log_dbh_bin_h")),
                                ~as.character(.)) %>% 
                # ~as.character(round(exp(.),2))) %>% # marche mais désorganise les labels
      unite(col=dbh_bin, log_dbh_bin_l, log_dbh_bin_h, sep="-") %>% 
      
      ggplot(aes(dbh_bin, logTransmittance, col = Presence)) +
      theme_minimal() +
      geom_boxplot() +
      geom_vline(xintercept = log(10)) + # 10 cm DBH
      scale_y_continuous("Light Transmittance (%)",
                         n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
      # scale_x_continuous("Diameter at Breast Height (DBH, cm)",
      #                    n.breaks = 10, labels = ~round(exp(.),2)) + # delog
      
      scale_color_manual(values = c("Absence" = "#999999",
                                    "Presence"= "#009E73")) + # 
      theme(plot.title = element_text(colour = cl)) +
      labs(title = paste(sp[p], " (N: ",N,")", sep=""), x = "log(DBH) (cm)")
  })
}

plots <- gridExtra::marrangeGrob(plist, nrow = 2, ncol = 2)
# plots

ggsave("Light_onto_niche_relativetothe_community_mean_debin.pdf",
       path = "//amap-data.cirad.fr/work/users/VincyaneBadouard/Inventories/Explo_plots",
       plots, width = 15, height = 10)

```

# Boxplots per size cass
```{r}
# "1-5","5-10","10-20",">20"
# "1-3","3-8","8-20",">20"
# "1-3","3-10","10-25",">25"

Names <- names(datalist)
datalist <- lapply(names(datalist), function(name) {
  
  datalist[[name]] <- datalist[[name]] %>%
    mutate(Strategy = ifelse(is.na(Strategy), "Canopy species", Strategy)) %>% 
    mutate(Size = factor(case_when(
      # DBHcor < 10 ~ "1-10",
      # DBHcor >= 10 ~ ">10"), levels = c("1-10",">10")) 
      
      # DBHcor < 5 ~ "1-5",
      # DBHcor >= 5 & DBHcor < 10 ~ "5-10",
      # DBHcor >= 10 & DBHcor < 20 ~ "10-20",
      # DBHcor >= 20 ~ ">20"
      Strategy == "Canopy species" & DBHcor < 3 ~ "1-3",
      Strategy == "Canopy species" & DBHcor >= 3 & DBHcor < 10 ~ "3-10",
      Strategy == "Canopy species" & DBHcor >= 10 & DBHcor < 25 ~ "10-25",
      Strategy == "Canopy species" & DBHcor >= 25 ~ ">25",
      
      Strategy == "Understory species" & DBHcor < 2.5 ~ "< 2.5",
      Strategy == "Understory species" & DBHcor >= 2.5 ~ ">= 2.5"),
      levels = c("1-3","3-10","10-25",">25", "< 2.5",">= 2.5"))
    )
  
  datalist[[name]]  # Return modified data frame
})

names(datalist) <- Names 
```

```{r}
plist <- vector('list', length(sp))

for(p in 1:length(sp)){
  plist[[p]] <- local({
    # p = 33
    dataS <- datalist[names(datalist) %in% sp[p]][[sp[p]]] %>% 
      mutate(Presence = recode(as.character(Presence),
                               "1" = "Presence", "0" = "Absence")) 
    
    if(all(is.na(dataS[dataS$Presence=="Presence",]$Strategy))){cl = "black"
    }else if(unique(na.omit(dataS[dataS$Presence=="Presence",]$Strategy))=="Canopy species"){cl = "#E7B800"
    }else if(unique(na.omit(dataS[dataS$Presence=="Presence",]$Strategy=="Understory species"))){cl = "#009E73"}
    
    N <- nrow(dataS[dataS$Presence=="Presence",])
    
    test <- dataS %>% 
      mutate(cl = cl) %>% 
      mutate(Size = factor(case_when(
      DBHcor < 5 ~ "1-5",
      DBHcor >= 5 & DBHcor < 10 ~ "5-10",
      DBHcor >= 10 & DBHcor < 20 ~ "10-20",
      DBHcor >= 20 ~ ">20"), levels = c("1-5","5-10","10-20",">20")))
# case_when(
#   cl == "#E7B800" & DBHcor < 3 ~ "1-3",
#   cl == "#E7B800" & DBHcor >= 3 & DBHcor < 10 ~ "3-10",
#   cl == "#E7B800" & DBHcor >= 10 & DBHcor < 25 ~ "10-25",
#   cl == "#E7B800" & DBHcor >= 25 ~ ">25",
# 
#   cl == "#009E73" & DBHcor < 2.5 ~ "< 2.5",
#   cl == "#009E73" & DBHcor >= 2.5 & DBHcor < 16 ~ "2.5-16")) %>%
# filter(!is.na(Size))
#     
#     if(cl == "#E7B800"){test$Size <- factor(test$Size,
#                                             levels = c("1-3","3-10","10-25",">25"))
#     }else if(cl == "#009E73"){test$Size <- factor(test$Size,
#                                                   levels = c("< 2.5","2.5-16"))}
    
    label <- test %>% 
      group_by(Presence, Size) %>% 
      summarise(N = paste("N: ", n()))
    
    
    # loged bins
    test %>% 
      ggplot(aes(Size, logTransmittance, col = Presence, fill = Presence)) +
      theme_minimal() +
      geom_violin(aes(alpha = 0.5), position = position_dodge(width = 0.9)) + # trim = F, draw_quantiles = c(0.25, 0.5, 0.75)
      geom_boxplot(aes(alpha = 0.5), col = "black",position = position_dodge(width = 0.9), width=0.2) +
      
      scale_y_continuous("Light Transmittance (%)",
                         n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
      scale_color_manual(values = c("Absence" = "#999999",
                                    "Presence"= "#009E73")) +
      scale_fill_manual(values = c("Absence" = "#999999",
                                   "Presence"= "#009E73")) + 
      
      
      geom_text(data = label, aes(label = N, y = 0.3), size = 3.5,
                position = position_dodge(width = 0.95), show.legend = F) +
      
      theme(plot.title = element_text(colour = cl)) +
      guides(alpha = FALSE) +
      labs(title = paste(sp[p], " (N: ",N,")", sep=""), x = "DBH (cm)")
  })
}

plots <- gridExtra::marrangeGrob(plist, nrow = 2, ncol = 2)
# plots

ggsave("Light_onto_niche_relativetothe_community_boxplots_size_class_debin.pdf",
       path = "//amap-data.cirad.fr/work/users/VincyaneBadouard/Inventories/Explo_plots",
       plots, width = 15, height = 10)

```

# Size class abundances
```{r}
st <- "Canopy species" # "Understory species"
datalist[[1]] %>% 
  filter(ScientificName %in% sp) %>% 
  group_by(ScientificName, factor(Size)) %>% 
  mutate(N = n()) %>% 
  ungroup() %>% 
  select(ScientificName, Strategy, Size, N) %>% 
  unique() %>% 
  # arrange(ScientificName, Size) %>% 
  # group_by(ScientificName) %>% 
  # filter(!all(N == sort(N, decreasing = TRUE))) %>%
  # ungroup() %>% 
  filter(Strategy==st) %>% 
  
  ggplot(aes(x= Size, y= N, col= ScientificName, group=ScientificName)) + # , alpha= N>30
  theme_minimal() +
  # ylim(0,30) +
  guides(color = FALSE) +
  # guides(col = guide_legend(ncol = 2)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 10) + 
  scale_y_continuous(trans="log", n.breaks = 8) +
  labs(title=st)

```

```{r}
datalist[[1]] %>% 
  filter(ScientificName %in% sp) %>% 
  filter(Strategy=="Understory species") %>% 
  filter(DBHcor >10) # 11
# 10-20:
# Talisia_guianensis 1
# Licaria_debilis	1	
# Guarea_costata	1
# Anaxagorea_dolichocarpa	8

max((datalist[[1]] %>% 
       filter(Strategy=="Understory species"))$DBHcor)

```

```{r}
st <- "Understory species"
datalist[[1]] %>% 
  filter(ScientificName %in% sp) %>% 
  group_by(ScientificName, factor(Size)) %>% 
  mutate(N = n()) %>% 
  ungroup() %>% 
  select(ScientificName, Strategy, Size, N) %>% 
  unique() %>% 
  # arrange(ScientificName, Size) %>% 
  # group_by(ScientificName) %>% 
  # filter(!all(N == sort(N, decreasing = TRUE))) %>%
  # ungroup() %>% 
  filter(Strategy==st) %>% 
  
  ggplot(aes(x= Size, y= N, col= ScientificName, group=ScientificName)) + # , alpha= N>30
  theme_minimal() +
  # ylim(0,30) +
  # guides(color = FALSE) +
  # guides(col = guide_legend(ncol = 2)) +
  geom_point() +
  geom_line() +
  geom_hline(yintercept = 10) + 
  scale_y_continuous(trans="log", n.breaks = 8) +
  labs(title=st)
```
