---
title: "Understory inventories - data exploration"
author: "Vincyane"
date: "`r Sys.Date()`"
output: html_document
---
- distributions d’abondances des espèces (pas sure de savoir quoi ploter) (voir Clean_inventory.Rmd)
- distrib diamétrique par espèce : DBH_distributions_by_sp.Rmd
- carte env - espèce, DBH
- relations env -distrib : density plot ( x : env, y abondances par espèce)
- ou points en couleur selon le diamètre

# Packages
```{r Setup, include = F}
library(readr)
library(tidyverse)
library(data.table)
```

# Load cleaned data
```{r, include = F}
Understory <- read_csv("~/PhD/Inventories/Data/Understory/Paracou/ALT_Paracou_9ha_Filtred.csv")
```

# Distributions d’abondances des espèces
```{r}
length(unique(Understory$ScientificName)) # 200
# population[order(population$age),]

Understory %>%
  select(ScientificName, N, Strategy) %>% 
  # group_by(ScientificName) %>% 
  # summarise(N = n()) %>% 
  arrange(desc(N)) %>% 
  mutate(ScientificName = factor(ScientificName, levels= unique(ScientificName))) %>% 
  ggplot(aes(x= ScientificName, fill = Strategy)) + # fill = as.factor(Strategy)
  geom_bar(alpha=0.9) + # fill="#69b3a2", color="#e9ecef"
  
  theme(axis.title.x = element_blank(),
        axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1, size=7),
        axis.title.y = element_text(size=14), axis.text.y = element_text(size=16),
        legend.position="bottom", legend.title= element_text(size=16), legend.text= element_text(size=16)) +

  labs(y = "Abundances")

ggsave(paste("ALT", unique(Understory$Site), unique(Understory$Plot),"Species_abundances_sup30ind.png", sep="_"),
       path = "D:/Mes Donnees/PhD/Figures/inventory", width = 50, height = 10, units = "cm", dpi=800, bg="white")
```

