---
title: "Sampling"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---

# Species
```{r setup}
library(tidyverse)
library(cmdstanr)
library(bayesplot)
library(scales)

sp <- (read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,2]) # 75


# sp <- c("Licania_membranacea", "Symphonia_sp.1", "Piparea_multiflora", "Iryanthera_hostmannii", "Tabernaemontana_macrocalyx") # 4 forms
# sp <- "Symphonia_sp.1"

Var <- c("TWI", "HAND")
```

```{r fit}
fit <- list()
for(S in sp){
  for(V in Var){
    tryCatch({
      chain_path <- file.path("Chains", "Affine", V, S)
      fit[[S]][[V]] <- as_cmdstan_fit(list.files(chain_path,
                                                 full.names = TRUE))},
      error=function(e){cat("ERROR :",S, V, conditionMessage(e), "\n")}
    )
  }
}
# names(fit[["Symphonia_sp.1"]])
```


# Compute and compare BIC for each species between variables HAND and TWI
For each species and each variable compute BIC and compare BIC for each species between variables
Models with lower BIC are generally preferred
```{r BIC df}
BIC_df <- data.frame(crossing(
  Species = sp,
  Variable = Var,
  k= NA,
  L= NA))

for(S in sp){
  for(V in Var){
    BIC_df <- BIC_df %>% 
      mutate(k = ifelse(Species==S & Variable==V,
                        length(fit[[S]][[V]]$metadata()$stan_variables[!fit[[S]][[V]]$metadata()$stan_variables %in% c("lp__", "p", "a","O","gamma","beta2_p")]), k), # parameters nbr
             L = ifelse(Species==S & Variable==V, max(fit[[S]][[V]]$draws("lp__")), L), # the maximized value of the likelihood function of the model (lp__ = log probability value that will be returned by the log probability function)
      )
  }}

BIC_df <- BIC_df %>% 
  mutate(N = 47850, # observations nbr
         BIC = k*log(N) - 2*L 
  ) %>% 
  select(Species, Variable, BIC) %>% 
  pivot_wider(names_from = Variable,
              values_from = BIC,
              names_glue = "{.value}_{Variable}") %>% 
  # Compare BIC between variables for each species
  rowwise() %>% 
  mutate(Diff = BIC_HAND - BIC_TWI) %>% 
  mutate(test = ifelse(BIC_TWI <= BIC_HAND,T,F)) %>% 
  mutate(HAND = ifelse(BIC_HAND < BIC_TWI & abs(Diff)>2,T,F)) %>% 
  mutate(TWI = ifelse(BIC_TWI < BIC_HAND & abs(Diff)>2,T,F))

nrow(BIC_df %>% filter(test==T)) # 34
nrow(BIC_df %>% filter(HAND==T)) # 23
nrow(BIC_df %>% filter(TWI==T)) # 31 -> best BIC is for TWI
nrow(BIC_df %>% filter(HAND==F,TWI==F)) # 21

```

```{r}
write.csv(BIC_df, "//amap-data.cirad.fr/work/users/VincyaneBadouard/Modelisation/GoodnessOfFit/BIC/BIC_affine_HAND_vs_TWI.csv")
# BIC_df <- read_csv("//amap-data.cirad.fr/work/users/VincyaneBadouard/Modelisation/GoodnessOfFit/BIC/BIC_affine_HAND_vs_TWI.csv")
```

```{r}
BIC_df %>% filter(HAND==T) %>% arrange(Diff)
```

```{r}
S_sqrt <- function(x){sign(x)*sqrt(abs(x))}
IS_sqrt <- function(x){x^2*sign(x)}
S_sqrt_trans <- function() trans_new("S_sqrt",S_sqrt,IS_sqrt)

ggplot(BIC_df, aes(Diff)) +
  geom_density(fill = "lightgrey", col = NA) +
  theme_minimal() +
  geom_vline(xintercept = 0) +
  geom_vline(xintercept = c(-2, 2), linetype = "dashed") +
  scale_x_continuous(trans = "S_sqrt", 
                     breaks = c(-10, -2, 0, 2, 10, 100),
                     name = "BIC difference (HAND - TWI)") +
  # n species with bic diff < -2 (HAND pref)
  annotate("text", x = -7, y = 0.05, col="#D55E00",
           label = paste0(sum(BIC_df$Diff < -2), "/", nrow(BIC_df))) +
  # n species with bic diff >2 (TWI pref)
  annotate("text", x = 9, y = 0.05, col="#0072B2",
           label = paste0(sum(BIC_df$Diff > 2), "/", nrow(BIC_df))) +
  ylab("Density")

ggsave("BIC_HAND_vs_TWI.png", path = "D:/Mes Donnees/PhD/Figures/Modelisation/",
       width = 15, height = 15, units = "cm", dpi=800, bg="white")
```

```{r}
library(patchwork)
library(ggpubr)
var <- BIC_df %>% 
  select(Species, BIC_HAND, BIC_TWI) %>% 
  gather(Variable, BIC, -Species) # = pivot_longer

g1 <- ggpaired(var, x = "Variable", y = "BIC", # boxplots liés par des lignes
               color = "Variable", line.color = "gray", line.size = 0.4,
               palette = "jco") +
  stat_compare_means(paired = TRUE, vjust=-.8, hjust=.5) + # Mean Comparison P-values
  # test de la somme des rangs de Wilcoxon : test statistique non paramétrique qui permet de tester l'hypothèse selon laquelle les distributions de chacun de deux groupes de données sont proches
  # not significantly different
  scale_y_log10() +
  guides(color = FALSE) +
  ylab("BIC") +
  theme(axis.title.x = element_blank()) +
  scale_x_discrete(labels = c("HAND", "TWI"))

shape <- read_csv("//amap-data.cirad.fr/work/users/VincyaneBadouard/Modelisation/GoodnessOfFit/BIC/BIC_MNT_affine_vs_quadratic.csv") %>%
  select(Species, BIC_Affine, BIC_Quadratic) %>%
  gather(Variable, BIC, -Species)

g2 <- ggpaired(shape, x = "Variable", y = "BIC",
               color = "Variable", line.color = "gray", line.size = 0.4,
               palette = "jco") +
  stat_compare_means(paired = TRUE, vjust=-.8, hjust=.45) + # Mean Comparison P-values
  # test de la somme des rangs de Wilcoxon : test statistique non paramétrique qui permet de tester l'hypothèse selon laquelle les distributions de chacun de deux groupes de données sont proches
  # significantly different
  scale_y_log10() +
  guides(color = FALSE) +
  ylab("BIC") +
  theme(axis.title.x = element_blank()) +
  scale_x_discrete(labels = c("Affine", "Quadratic"))

g1 + g2

ggsave("BIC_topo_form_variable.png", path = "D:/Mes Donnees/PhD/Figures/Modelisation/",
       width = 20, height = 15, units = "cm", dpi=800, bg="white")

```

# List version
```{r BIC list}
BIC <- list()

for(S in sp){
  for(V in Var){
    
    k <- length(fit[[S]][[V]]$metadata()$stan_variables[!fit[[S]][[V]]$metadata()$stan_variables %in% c("lp__", "p", "a","O","gamma","beta2_p")]) # parameters nbr
    N <- 47850 # observations nbr
    L <- max(fit[[S]][[V]]$draws("lp__"))# the maximized value of the likelihood function of the model (fits[[f]]$summary("lp__"))
    
    BIC[[S]][[V]] <- k*log(N) - 2*L
    
  }
}
```

```{r test print}
for(S in sp){
  
  test <- BIC[[S]][["HAND"]] <= BIC[[S]][["TWI"]]
  
  if(test) print(paste(S, "- Lower BIC is for variable: HAND:", round(BIC[[S]][["HAND"]], 1),"vs",round(BIC[[S]][["TWI"]], 1)))
  if(test==F) print(paste(S, " - Lower BIC is for variable: TWI"))
  
}
```

