---
title: "Diagnose species"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
params:
  species: Licania_membranacea
---

```{r setup, include=F}
library(tidyverse)
library(cmdstanr)
library(bayesplot)
```

```{r fit}
print(params$species)
chain_path_A <- file.path("Chains", "Affine", params$species)
fit_A <- as_cmdstan_fit(list.files(chain_path_A, full.names = TRUE))

chain_path_Q <- file.path("Chains", "Quadratic", params$species)
fit_Q <- as_cmdstan_fit(list.files(chain_path_Q, full.names = TRUE))
```

```{r chains}
fit_A$draws(c("alpha", "beta1")) %>% 
  mcmc_trace() +
  labs(title= "Affine")

fit_Q$draws(c("alpha", "beta1", "beta2")) %>% 
  mcmc_trace() +
  labs(title= "Quadratic")
```

```{r posteriors}
fit_A$draws(c("alpha", "beta1")) %>% 
  mcmc_dens() +
  labs(title= "Affine")

fit_Q$draws(c("alpha", "beta1", "beta2")) %>% 
  mcmc_dens() +
  labs(title= "Quadratic")
```

```{r predictions}
for(fit in c(fit_A, fit_Q)){
  
  model_name <- ifelse("beta2" %in% fit$summary()$variable, "Quadratic", "Affine")

  print(
    fit$summary("p") %>% # p posterior
      mutate(x = seq(5.7325, 23.61375, length.out = 100)) %>% # prediction environment
      ggplot(aes(x = x)) +
      theme_minimal() +
      geom_point(aes(y = median), size=0.7) + # p posterior median
      geom_ribbon(aes(ymin = q5, ymax = q95), color = 'red', alpha = 0.2) + # P quantiles
      # geom_vline(xintercept  = fits[[f]]$summary("O")$median, color = "#00AFBB", linewidth=1) + # Opt median
      # geom_vline(xintercept  = fits[[f]]$summary("O")$q5, linetype="dashed") + # Opt Q5%
      # geom_vline(xintercept  = fits[[f]]$summary("O")$q95, linetype="dashed") + # Opt Q95%
      labs(title= model_name)
  )
}
```




