# Prepare data

# Packages
```{r Setup, include = F}
library(readr)
library(tidyverse)
```

```{r, include = F, message=F}
Inv <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/P16_2019_Paracou_InvandEnv.csv") # 47 850

sp <- read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,3] # 75
# length(unique(sp))
# sp %>% 
#   filter(ScientificName_TreeDataCor !=ScientificName )
```

```{r Sp number, eval=F}
(nrow(Inv %>% filter(ScientificName %in% sp))/nrow(Inv))*100 # the 75 sp corrsponds to 54% of the total stems number (pas les 70 sp et les catégories dbh d'au moins 10 ind)


Inv %>%
  # filter(grepl("_sp", ScientificName) & grepl("\\.", ScientificName)) %>%
  # filter(grepl("_cf_", ScientificName)) %>%
  # filter(grepl("Indet", ScientificName)) %>%
  # filter(grepl("_aff", ScientificName) & grepl("\\.", ScientificName)) %>%
  # filter(grepl("subsp", ScientificName) & grepl("\\.", ScientificName)) %>%
  # filter(grepl("var", ScientificName) & grepl("\\.", ScientificName)) %>%
  select(ScientificName) %>% unique()

allsp <- Inv %>%
  filter(!is.na(ScientificName)) %>%
  filter(ScientificName!="Tres haut") %>%
  filter(ScientificName!="Rinorea_idem181298") %>%
  filter(!grepl("indet", ScientificName)) %>%
  filter(!grepl("Indet", ScientificName)) %>%
  filter(!grepl("aceae", ScientificName)) %>%
  filter(!(grepl("_sp", ScientificName) & grepl("\\.", ScientificName))) %>% # only genus
  filter(!(grepl("_aff", ScientificName) & grepl("\\.", ScientificName))) %>% # identif not sure
  filter(!grepl("_cf_", ScientificName)) %>% 	
  # filter(!(grepl("subsp", ScientificName) & grepl("\\.", ScientificName))) %>%
  # filter(!(grepl("var", ScientificName) & grepl("\\.", ScientificName))) %>%
  arrange(ScientificName) 

(nrow(allsp)/nrow(Inv))*100 # 86% stems botanicaly identified

allsp %>% 
  select(ScientificName) %>%
  unique()
# 576 sans les sp et sp numéro


Inv %>%
  filter(Strategy == "Understory species") %>% 
  select(ScientificName, Strategy) %>% 
  unique() # 29 understory sp

```

```{r}
Inv <- Inv %>% 
  mutate(logTransmittance =  log(Transmittance)) %>% 
  mutate(logTWI = log(TWI)) %>% 
  mutate(logDBH = log(DBHcor))

```

```{r}
summary(Inv)
```

# Abundance table
```{r}
data <- Inv %>%
  filter(ScientificName %in% sp) %>% 
  mutate(Size = factor(case_when(
    DBHcor < 3 ~ "1-3",
    DBHcor >= 3 & DBHcor < 10 ~ "3-10",
    DBHcor >= 10 & DBHcor < 25 ~ "10-25",
    DBHcor >= 25 ~ ">25"), levels = c("1-3","3-10","10-25",">25"))
  ) %>% 
  group_by(ScientificName, Size) %>% 
  summarise(N = n()) %>% 
  pivot_wider(names_from = Size,
              values_from = N)

data[is.na(data)] <- 0

data <- data %>% 
  group_by(ScientificName) %>% 
  mutate(N = sum(`1-3`,`3-10`,`10-25`,`>25`)) %>% 
  select(ScientificName, N, `1-3`,`3-10`,`10-25`,`>25`)

length(unique(data$ScientificName))

write_csv(data, "D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_abundance_DBHclass_25ha.csv")
```


# Keep environment values for predictions
50 values each
```{r}
Combin <- read_csv("../../../PhD_cluster/Data/Combin_Sp_DBHclas.csv") %>% 
  select(-ID, -Species) %>% 
  unique()

```

```{r}
Np <- 50 # number of predictions

x <- Inv %>% 
  select(DBHcor, logTransmittance, logTWI)

Community <- data.frame(
  DBH_classes = 'All',
  Lightp = seq(min(x$logTransmittance), max(x$logTransmittance), length.out = Np),
  Topographyp = seq(min(x$logTWI), max(x$logTWI), length.out = Np)
)

d <- list()
for(i in 1:nrow(Combin)){
  # i=2
  x <- Inv %>% 
    filter(DBHcor >= Combin[i,]$Min & DBHcor < Combin[i,]$Max) # only the DBH class)
  
  d[[i]] <- data.frame(
    DBH_classes = Combin[i,]$DBH_classes,
    Lightp = seq(min(x$logTransmittance), max(x$logTransmittance), length.out = Np),
    Topographyp = seq(min(x$logTWI), max(x$logTWI), length.out = Np)
    # Topographyp = median(x[x$Presence==1,]$logTWI)
  )
  
}

Envpred <- do.call("rbind",d) %>% rbind(Community) # 5*50 = 250
unique(Envpred$DBH_classes)

write_csv(Envpred, "D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Envrmt_prediction_25ha.csv")
```


# Create presence-absence data format for each species
```{r}
# Create a list of the inventory replicated, 1 per ScientificName
datalist <- replicate(length(sp), Inv, simplify = F) 
names(datalist) <- sp # 1 per ScientificName

# Presence=1 if it's the interest species, 0 if not
datalist <- lapply(names(datalist), function(name) {
  datalist[[name]]$Presence <- ifelse(
    !is.na(datalist[[name]]$ScientificName) & datalist[[name]]$ScientificName == name, 1, 0)
  
  datalist[[name]]  # Return modified data frame
})
names(datalist) <- sp # 75

# view(datalist[["Anaxagorea_dolichocarpa"]])
```

```{r}
save(datalist, file= "D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha.Rdata")

# load("D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha.Rdata")
```

# Balance presence and absence
```{r}
# Take all the presences and the same nbr of absences (allready done)
# pres <- Residuals %>% filter(y==1)
# abs <- Residuals %>%
#   filter(y==0) %>%
#   sample_n(nrow(pres))
# samp <- bind_rows(pres, abs)

datalist_bal <- lapply(names(datalist), function(name) {
  
  pres <- datalist[[name]] %>% filter(Presence==1)
  abs <- datalist[[name]] %>%
    filter(Presence==0) %>%
    sample_n(nrow(pres))
  samp <- bind_rows(pres, abs)
  datalist[[name]] <- samp
  datalist[[name]]  # Return modified data frame
})

names(datalist_bal) <- sp # 75

```

```{r}
save(datalist_bal, file= "D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha_balanced.Rdata")

# load("D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha_balanced.Rdata")
```

# Join eigenvectors
```{r}
load("D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha.Rdata")
```

```{r}
filelist <- list.files("D:/Mes Donnees/PhD/Inventories/Data/Agregation/Eigenvectors/Per_species_25ha/", full.names=T)
eigenval <- lapply(filelist, read_csv)
filelist <- gsub("D:/Mes Donnees/PhD/Inventories/Data/Agregation/Eigenvectors/Per_species_25ha/", "", filelist)
filelist <- gsub(".csv", "", filelist)

names(eigenval) <- filelist
```

```{r}
datalist_eig <- datalist

# str(datalist_eig[[1]])

datalist_eig <- lapply(names(datalist), function(name) {
  # name = "Sextonia_rubra"
  if(name %in% names(eigenval) & ncol(eigenval[[name]])>0){
    datalist_eig[[name]] <- datalist_eig[[name]] %>%
      # left_join(unique(eigenval[[name]]), by=c("Xutm", "Yutm"), copy = T)
      bind_cols(eigenval[[name]])
    
  }
  datalist_eig[[name]]  # Return modified data frame
})

names(datalist_eig) <- names(datalist) 

datalist_eig[["Eperua_falcata"]]
```


```{r}
save(datalist_eig, file= "D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha_eigenvectors.Rdata")

# load("D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Realsp_25ha_eigenvectors.Rdata")
```

