---
title: "Chapter 2 plots"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---
```{r setup}
library(tidyverse)
library(cmdstanr)
library(bayesplot)
library(patchwork)
library(grid)
library(stringr)

sp <- read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,3] # 75
abund <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_abundance_DBHclass_9ha.csv")

PATH <- "//amap-data.cirad.fr/work/users/VincyaneBadouard/Modelisation/Plots/Light_topo/Autocor"

datap <- read_csv(paste(PATH, "/dataplot.csv", sep='')) %>% 
  mutate(bigdiff = ifelse(ScientificName %in% c("Qualea_rosea", "Pouteria_guianensis"), T, F)) %>% 
  select(-Species_code)
```


```{r Species code}
# databp %>% 
#   select(Species) %>% 
#   separate(Species, c("genus", "species")) %>% 
#   mutate(g = str_sub(genus, 1, 3), 
#          s = ifelse(
#            g == "Esc",
#            str_sub(species, 1, 3),
#            str_sub(species, 1, 2)
#          )) %>% 
#   mutate(code = paste0(g, "-", s))

datap <- datap %>% 
  # select(Species) %>% 
  separate(Species, c("genus", "species"), remove=F) %>% 
  mutate(
    g = ifelse(
      str_sub(genus, 1, 2) %in% c("Po", "Ta", "Co"),
      str_sub(genus, 1, 3),
      str_sub(genus, 1, 2)
    )
  ) %>% 
  mutate(
    s = ifelse(
      g == "Es",
      str_sub(species, 1, 3),
      str_sub(species, 1, 2)
    )
  ) %>% 
  mutate(Species_code = paste0(g, "_", s))

spcode <- datap %>% select(ScientificName, Species, Species_code, H_allometry) %>% unique()
# write_csv(spcode, 'D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_code.csv')

```

```{r, eval=F}
# 25 ha
abund <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_abundance_DBHclass_25ha.csv") %>% select(-Species_code)

abund <- spcode %>% left_join(abund, by="Species") %>% select(-ScientificName) %>% 
  arrange(Species)
write_csv(abund, "D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_abundance_DBHclass_25ha.csv")

# 9 ha
abund <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_abundance_DBHclass_9ha.csv") %>% select(-Species_code)

abund <- spcode %>% left_join(abund, by="Species") %>% select(-ScientificName) %>% 
  arrange(Species)
write_csv(abund, "D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/Species_abundance_DBHclass_9ha.csv")

```

# Biplot a vs tau
a in y, tau in x

```{r}
databp <- datap %>% 
  select(-Q95) %>% 
  select(-c(outer_width, inner_width, point_est, Sg_effect)) %>% 
  rename(Q5 = ll, Q80 = hh, median = m, Q50_0 = l, Q50_1 = h) %>% 
  filter(parameter %in% c("tau", "a", "O")) %>% 
  pivot_wider(names_from = parameter, values_from = c(Q5, Q50_0, median, Q50_1, Q80),
              names_glue = "{parameter}_{.value}") %>% 
  # Light effect (not flat)
  mutate(Sg_effect = ifelse(a_median > -0.02, F, T)) %>% # no light effect
  # mutate(O_median = ifelse(!Sg_effect, NA,O_median)) %>% # no light effect
  
  mutate(Incertitude = a_Q80 - a_Q5) %>% # 50% CI : O_Q50_1-O_Q50_0 ; 80% CI : O_Q80-O_Q5
  # tau significantly different of 0
  mutate(Tau_effect = ifelse(tau_Q5<0 & 0<tau_Q80, F, T))


# databp <- databp %>%
#   mutate_at(vars(c(a_Q5, a_Q50_0, a_median, a_Q50_1, a_Q80)), ~ (-.))
```



```{r}
my_trans <- scales::trans_new(
  "my_trans",
  function(x) sqrt(-x),
  function(y) -y^2
)

ggplot(databp) +
  theme_minimal() + 
  geom_vline(xintercept = 0, col="#999999", linetype = "dashed") +
  geom_hline(yintercept=-0.02, linetype = "dashed", col = "#999999") +
  
  geom_point(aes(x= tau_median, y = a_median,
                 col= O_median, size=Incertitude, shape= Tau_effect)) + 
  
  scale_shape_manual(values=c("FALSE" = 1, "TRUE" = 19),
                     breaks = c("TRUE","FALSE"),
                     labels = c("significant","n.s.")) +
  
  viridis::scale_color_viridis(begin =0.45, lim = c(-7,0), breaks = log(c(0.1, 1,5,15,100)/100), labels = ~round(exp(.)*100,2)) +
  scale_size_continuous(range = c(0.5,4), trans = 'reverse') +
  
  ggrepel::geom_text_repel(aes(x= tau_median, y = a_median, label = Species_code), col = "black", size = 3) +
  
  scale_y_continuous(trans = my_trans, breaks = c(0, - .02, -.1, -.2, -.3)) +
  
  # Annotations
  theme(plot.margin = unit(c(1,1,1,3), "lines")) +
  coord_cartesian(clip = "off") + 
  
  # annotation_custom(textGrob("Drier", gp=gpar(col="#999999")),
  #                   xmin= -3,xmax=-3,ymin=-0.02,ymax=-0.02) +
  # annotation_custom(textGrob("Wetter", gp=gpar(col="#999999")),
  #                   xmin= 2,xmax=2,ymin=-0.02,ymax=-0.02) +
  # 
  # annotation_custom(textGrob("Flat", gp=gpar(col="#999999")),
  #                   ymin= .07,ymax=.07,xmin=-4.1,xmax=-4.1) +
  # annotation_custom(textGrob("Wide", gp=gpar(col="#999999")),
  #                   ymin= .18,ymax=.18,xmin=-4.1,xmax=-4.1) +
  # annotation_custom(textGrob("Narrow", gp=gpar(col="#999999")),
  #                   ymin= .55,ymax=.55,xmin=-4.1,xmax=-4.1) +
  
  # annotation_custom(textGrob("Drier", gp=gpar(col="#999999")),
  #                   xmin= -3,xmax=-3,ymin=0,ymax=0) +
  # annotation_custom(textGrob("Wetter", gp=gpar(col="#999999")),
  #                   xmin= 2,xmax=2,ymin=0,ymax=0) +
  
  annotation_custom(textGrob("Flat", gp=gpar(col="#999999")),
                    ymin= -0.01,ymax=-0.01,xmin=-4.1,xmax=-4.1) +
  annotation_custom(textGrob("Wide", gp=gpar(col="#999999")),
                    ymin= -0.03,ymax=-0.03,xmin=-4.1,xmax=-4.1) +
  annotation_custom(textGrob("Narrow", gp=gpar(col="#999999")),
                    ymin= -0.3,ymax=-0.3,xmin=-4.1,xmax=-4.1) +
  
  
  guides(size = guide_legend(nrow=2, title.position = 'top', order =2),
         shape = guide_legend(nrow=2, title.position = 'top', order =1),
         col = guide_colourbar(title.position = 'top', order =3)) +
  
  theme(axis.title.y = ggtext::element_markdown(),
        legend.title = ggtext::element_markdown(),
        legend.position="bottom") + # , legend.box="vertical"
  labs(x= expression(Topographic~Wetness~Index~(TWI)~linear~effect~"(" * tau * ")"),
       y= "Light niche width (*a*)", size = '*a* 80% incertitude',
       col ="Light optimum (*O*)<br>(% transmittance)",
       shape = 'Topographic effect (τ)')

# alpha sur les postériors imprécis

ggsave("a_tau_biplot.png", path = PATH,
       width = 18, height = 18, units = "cm", dpi=800, bg="white")

```
# Method plot
```{r}
#| fig-width: 10
#| fig-height: 3
tidyr::crossing(
  a = c(-0.02, -0.05, -0.15, -0.3), 
  O = -3,
  gamma = 0,
  Environment = (seq(-6,0, length.out =50)) 
) %>% 
  mutate(P = 1 / (1 + exp(-(a * (Environment - O)^2 + gamma)))) %>% 
  
  mutate(a = factor(a,
                    levels = c("-0.02", "-0.05", "-0.15", "-0.3"),
                    labels = c("Flat (a = -0.02)", "Very wide (a = -0.05)", "Wide (a = -0.15)", "Narrow (a = -0.3)"))) %>% 
  
  ggplot(aes(x=Environment, y=P, group = paste(O, a, gamma))) +
  geom_vline(xintercept = -3, linetype = "dashed") +
  geom_line(linewidth=1) +
  facet_wrap(~a, nrow=1) +
  
  scale_x_continuous(n.breaks = 5, labels = ~round(exp(.)*100,2)) + # delog
  
  labs(x='Light (% transmittance)', y= 'Species presence probability') +
  theme_minimal() +
  theme(panel.spacing = unit(1, "lines"))

ggsave("Methods_plot.png", path = PATH,
       width = 16, height = 6, units = "cm", dpi=800, bg="white") # 22
```

# TreeHeightQ95 vs O
```{r TreeHeightQ95 vs O}
test <- datap %>% 
  filter(parameter=='O'& Sg_effect) %>% 
  filter(TreeHeightQ95>15 & TreeHeightQ95<30)
exp(range((datap %>% 
             filter(parameter=='O'& Sg_effect) %>% 
             filter(TreeHeightQ95>15 & TreeHeightQ95<35))$m))*100 #  0.1512948 75.5910346 %T

datap %>% 
  filter(parameter=='O'& Sg_effect) %>% # & Sg_effect
  ggplot(aes(x=TreeHeightQ95, y=m)) + 
  theme_minimal() + 
  scale_y_continuous("O median (transmittance %)", n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
  ggrepel::geom_text_repel(aes(label = Species_code), col = "black", size = 2.3,
                           xlim=c(4,42), ylim = c(-7,0.5)) +
  geom_point() + # aes(col = H_allometry)
  
  ggpubr::stat_cor(method = "pearson", label.x = +6, label.y = .1) +
  # lines
  # geom_hline(aes(yintercept=log(5/100)), col = "red", linetype='dashed') +
  # geom_vline(aes(xintercept=25), col = "black", linetype='dashed') +
  # geom_vline(aes(xintercept=40), col = "black", linetype='dashed') +
  
  # scale_color_manual(name= "Allometry source",
  #                    values = c("Specific" = "black",
  #                               "Community"= "#999999")) +
  
  # scale_shape_manual(name= 'Flat light niche',
  #                    values=c("FALSE" = 19, "TRUE" = 1),
  #                    breaks = c("FALSE","TRUE")) +
  
  labs(x= "Species Q95% tree height (m)") +
  theme(legend.position="bottom")

ggsave("Light_topo_TreeHeightQ95_checkstrategies.png", path = PATH,
       width = 18, height = 10, units = "cm", dpi=800, bg="white")
```

# TreeHeightQ95 vs a
```{r TreeHeightQ95 vs a}

datap %>% 
  filter(parameter=='a') %>% 
  ggplot(aes(x=TreeHeightQ95, y=m)) + 
  theme_minimal() + 
  # lines
  geom_hline(aes(yintercept=-0.02), col = "grey", linetype='dashed') +
  
  ggrepel::geom_text_repel(aes(label = Species_code), col = "black", size = 2.3,
                           xlim=c(4,42), ylim = c(-0.3,0.015)) + # , force=25
  geom_point(aes(shape= m> -0.02)) + # col = H_allometry, 
  # geom_point(aes(col = bigdiff, shape=Sg_effect)) +
  
  ggpubr::stat_cor(method = "pearson", label.x = 6, label.y = 0.01) +
  
  # scale_color_manual(name= "Allometry source",
  #                    values = c("Specific" = "black",
  #                               "Community"= "#999999")) +
  
  # scale_y_continuous(trans = my_trans, breaks = c(0, -.1, -.2, -.3, - .02)) +
  
  scale_shape_manual(name= 'Flat light niche',
                     values=c("FALSE" = 19, "TRUE" = 1),
                     breaks = c("FALSE","TRUE")) +
  
  theme(axis.title = ggtext::element_markdown(),
        legend.title = ggtext::element_markdown(),
        legend.position="bottom") +
  labs(y= "Niche width (*a*)", x= "Species Q95% tree height (m)") +
  theme(legend.position="bottom")


ggsave("Light_width_TreeHeightQ95.png", path = PATH,
       width = 18, height = 10, units = "cm", dpi=800, bg="white")
```

# DBH Q95%
```{r DBH Q95%}
datap %>% 
  filter(parameter=='O' & Sg_effect) %>% 
  filter(!Species %in% c('Talisia_sylvatica', 'Votomita_guianensis')) %>% # because misidentifications so wrong Q95
  ggplot(aes(x=Q95, y=m)) + 
  theme_minimal() + 
  scale_y_continuous("O median (transmittance %)", n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
  ggrepel::geom_text_repel(aes(label = Species_code), col = "black", size = 2.3,
                           ylim = c(-7,0.5)) + # xlim=c(4,42),
  geom_point(aes(shape= !Sg_effect)) +
  # geom_point(aes(col = bigdiff, shape=Sg_effect)) +
  
  ggpubr::stat_cor(method = "pearson", label.x = +6, label.y = .1) +
  # lines
  # geom_hline(aes(yintercept=log(5/100)), col = "red", linetype='dashed') +
  # geom_vline(aes(xintercept=25), col = "black", linetype='dashed') +
  # geom_vline(aes(xintercept=40), col = "black", linetype='dashed') +
  
  scale_shape_manual(name= 'Flat light niche',
                     values=c("FALSE" = 19, "TRUE" = 1),
                     breaks = c("FALSE","TRUE")) +
  
  labs(x= "Species Q95% DBH (cm)") +
  theme(legend.position="bottom")

# Annotations
# theme(plot.margin = unit(c(.5,.5,1,.5), "lines")) + # 3e
# coord_cartesian(clip = "off") +
# 
# annotation_custom(textGrob("Understorey", gp = gpar(fontsize=10, col="#999999")),
#                   xmin= 15,xmax=15,ymin=-7.2,ymax=-7.2) +
# annotation_custom(textGrob("Mid-canopy", gp = gpar(fontsize=10, col="#999999")),
#                   xmin= 33,xmax=33,ymin=-7.2,ymax=-7.2) +
# annotation_custom(textGrob("Upper-canopy", gp = gpar(fontsize=10, col="#999999")),
#                   xmin= 45,xmax=45,ymin=-7.2,ymax=-7.2)

ggsave("Light_topo_DBHQ95_checkstrategies.png", path = PATH,
       width = 18, height = 10, units = "cm", dpi=800, bg="white")
```

# Compare with growth rate
Schmitt et al., 2023
O vs Gmax, H vs Gmax
```{r}
growth <- read_delim("D:/Mes Donnees/PhD/growthfull_S_Schmitt.tsv", 
                     delim = "\t", escape_double = FALSE, 
                     trim_ws = TRUE)  %>% 
  # select(idTree, species, gmax) %>% 
  mutate(species = str_replace(species, " ", "_")) %>%
  mutate(ScientificName_c = sub("\\..*", "", species)) %>%
  mutate(SubSpecies = str_extract(species,"(?<=\\.).*")) %>%
  rename(ScientificName_old = species,
         species = ScientificName_c) %>%
  mutate(species = str_remove(species," subsp")) %>%
  mutate(species = str_remove(species," var")) %>%
  mutate(species = str_replace(species, "Symphonia_sp", "Symphonia_sp.1"))

growth <- growth %>% # several measurement per species
  group_by(species) %>% 
  summarise(Gmax = exp(median(log(gmax))),
            Sd = sd(gmax)) %>% 
  separate(species, sep = ".subsp.", into = c("species", "Subspecies"), remove = F) %>% 
  mutate(species = data.table::tstrsplit(species, split = ".var\\.")[[1]])

# growth$species[!growth$species %in% datap$Species]

test <- datap %>% 
  filter(parameter=='O'& Sg_effect) %>% # & Sg_effect (59 sp)
  left_join(growth, by = c("ScientificName"="species")) # 42 match attendu

ggplot(test, aes(x=TreeHeightQ95, y=Gmax)) +
  theme_minimal() + 
  geom_errorbar(aes(ymin=Gmax-Sd, ymax=Gmax+Sd), col = "grey", width=.2) +
  geom_point() +
  coord_flip() +
  # scale_y_continuous(trans="log") +
  ggpubr::stat_cor(method = "pearson", label.x = 40, label.y = 0) +
  labs(x = "Species Q95% tree height (m)", y = "Species median growth potential")

ggsave("Gmax_Height.png", path = PATH,
       width = 10, height = 10, units = "cm", dpi=800, bg="white")

ggplot(test, aes(x=m, y=Gmax)) +
  theme_minimal() + 
  geom_errorbar(aes(ymin=Gmax-Sd, ymax=Gmax+Sd), col = "grey", width=.2) +
  geom_point() +
  coord_flip() +
  # scale_y_continuous(trans="log") +
  ggpubr::stat_cor(method = "pearson", label.x = 0, label.y = 2) +
  labs(x = "Light optimum", y = "Species median growth potential")

ggsave("Gmax_O.png", path = PATH,
       width = 10, height = 10, units = "cm", dpi=800, bg="white")

```

# Gmax, Dopt, Ks
```{r}
Dopt <- read_delim("~/PhD/dopt_S_Schmitt.tsv", 
                   delim = "\t", escape_double = FALSE, 
                   trim_ws = TRUE) %>% 
  unite(Genus, Species, col = "Species", sep = " ", remove = T) %>% 
  mutate(ScientificName_c = sub("\\..*", "", Species)) %>%
  mutate(SubSpecies = str_extract(Species,"(?<=\\.).*")) %>%
  rename(ScientificName_old = Species,
         Species = ScientificName_c) %>%
  mutate(Species = str_remove(Species," subsp")) %>%
  mutate(Species = str_remove(Species," var")) %>%
  mutate(Species = str_replace(Species, "Symphonia sp", "Symphonia sp.1")) %>% 
  select(Species, dopt)

Ks <- read_delim("~/PhD/ks_S_Schmitt.tsv", 
                 delim = "\t", escape_double = FALSE, 
                 trim_ws = TRUE) %>% 
  unite(Genus, Species, col = "Species", sep = " ", remove = T) %>% 
  mutate(ScientificName_c = sub("\\..*", "", Species)) %>%
  mutate(SubSpecies = str_extract(Species,"(?<=\\.).*")) %>%
  rename(ScientificName_old = Species,
         Species = ScientificName_c) %>%
  mutate(Species = str_remove(Species," subsp")) %>%
  mutate(Species = str_remove(Species," var")) %>%
  mutate(Species = str_replace(Species, "Symphonia sp", "Symphonia sp.1")) %>% 
  rename(Ks = mean) %>% 
  select(Species, Ks) %>% 
  group_by(Species) %>% 
  summarise(Ks = exp(median(log(Ks))),
            Sd = sd(Ks)) 

unique(GD$Categories)

GD <- test %>% 
  left_join(Dopt, by = "Species") %>% 
  left_join(Ks, by = "Species") 

ggplot(GD, aes(y=Gmax, x=dopt, col=m)) +
  theme_minimal() + 
  geom_point() +
  scale_colour_viridis_c(begin =0.45, lim = c(-7,0), breaks = log(c(0.1, 1,5,15,100)/100), labels = ~round(exp(.)*100,2)) +
  labs(x = "Species size at maximum growth rate (Dopt)",
       y = "Species median growth potential (Gmax)", col= "Light optimum")

ggsave("Gmax_Dopt_temperament.png", path = PATH,
       width = 10, height = 10, units = "cm", dpi=800, bg="white")

ggplot(GD, aes(y=Gmax, x=Ks, col=m)) +
  theme_minimal() + 
  geom_point() +
  scale_colour_viridis_c(begin =0.45, lim = c(-7,0), breaks = log(c(0.1, 1,5,15,100)/100), labels = ~round(exp(.)*100,2)) +
  labs(x = "Ontogenetic variation in growth rate (Ks)",
       y = "Species median growth potential (Gmax)", col= "Light optimum")

ggsave("Gmax_Ks_temperament.png", path = PATH,
       width = 10, height = 10, units = "cm", dpi=800, bg="white")
```

# Compare with succesionnal status
```{r}
Experts <- read_csv("~/PhD/Inventories/Data/Database_niche_littérature.csv") %>% 
  filter(OurSpecies) %>% 
  select(-OurSpecies, -`...11`) %>%
  select(Species, Temperament, SuccessionalStatus)

Experts %>% 
  filter(!is.na(SuccessionalStatus)) %>% # 23 sp
  filter(!Species %in% test$Species)

# unique(Experts$SuccessionalStatus)
# "Pioneer"
# "Primary forest understorey species"   
# "Fast growing\nearly successional"
# "Primary forest species that form mature forest canopy"

# "Late successional" : "Non-pioneer", "Fast growing late successional", "Slow growing late successional"  
```

```{r}
new <- test %>%
  left_join(Experts, by = "Species") %>% # 23 sp
  mutate(SuccessionalStatus =
           recode(SuccessionalStatus,
                  "Primary forest understorey species" = "Primary forest\nunderstorey species",
                  "Primary forest species that form mature forest canopy" = "Primary forest species\nthat form mature forest canopy", 
                  "Fast growing late successional" = "Fast growing\nlate successional",
                  "Slow growing late successional" = "Slow growing\nlate successional"
                  # "Non-pioneer" = "Late successional",
                  # "Fast growing late successional" = "Late successional",
                  # "Slow growing late successional" = "Late successional"
           )) %>% 
  # mutate(SuccessionalStatus =
  #          factor(SuccessionalStatus,
  #                 levels = c("Late successional",
  #                            "Primary forest\nunderstorey species",
  #                            "Primary forest species\nthat form mature forest canopy",
  #                            "Fast growing\nearly successional",
  #                            "Pioneer")))
  mutate(SuccessionalStatus = ifelse(Species %in% c("Pogonophora schomburgkiana", "Talisia mollis"), NA, SuccessionalStatus)) %>%
  mutate(SuccessionalStatus =
           factor(SuccessionalStatus,
                  levels = c("Non-pioneer",
                             "Slow growing\nlate successional",
                             "Fast growing\nlate successional",
                             "Primary forest\nunderstorey species",
                             "Primary forest species\nthat form mature forest canopy",
                             "Fast growing\nearly successional",
                             "Pioneer")))

label <- new %>% 
  group_by(SuccessionalStatus) %>% 
  summarise(N = paste("N: ", n()))

ggplot(new, aes(x=SuccessionalStatus, y= m)) +
  theme_minimal() + 
  geom_boxplot() +
  geom_text(data = label, aes(label = N, x= SuccessionalStatus),
            y = Inf, vjust = 1.5, show.legend = F) +
  scale_y_continuous("O median (transmittance %)", n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
  labs(y = "Light optimum", x = "Species successional status")

ggsave("Succession_O.png", path = PATH,
       width = 32, height = 8, units = "cm", dpi=800, bg="white")
```

# Compare with Vcmax
Amax : Maximum net photosynthesis rate
Vcmax25 : the maximum rate of carboxylation à 25°C for estimating CO2 assimilation (A) (fixation du carbone)
```{r}
Vcmax_Ver <- read_csv("~/PhD/Vcmax_Verryckt_et_al_reanalysees.csv") %>% 
  rename(Species=species) %>% 
  select(Species, Vcmax25)
Vcmax_Lamour <- read_csv("~/PhD/Vcmax25_Lamour.csv") %>% 
  select(Species, Vcmax25)

Vcmax <- Vcmax_Ver %>%
  bind_rows(Vcmax_Lamour) %>% 
  group_by(Species) %>% 
  summarise(Vcmax = median(Vcmax25),
            Sd = sd(Vcmax25)) 

test <- datap %>% 
  filter(parameter=='O'& Sg_effect) %>% # & Sg_effect ( sp)
  left_join(Vcmax, by = "Species") #  match attendu

ggplot(test, aes(x=m, y=Vcmax)) +
  theme_minimal() + 
  geom_errorbar(aes(ymin=Vcmax-Sd, ymax=Vcmax+Sd), col = "grey", width=.2) +
  geom_point() +
  coord_flip() +
  # scale_y_continuous(trans="log") +
  ggpubr::stat_cor(method = "pearson", label.x = 0, label.y = 2) +
  labs(x = "Light optimum", y = "Maximum rate of carboxylation at 25°C (Vcmax)")

ggsave("Vcmax_O.png", path = PATH,
       width = 10, height = 10, units = "cm", dpi=800, bg="white")
```
