---
title: "Diagnose species"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
params:
  species: Symphonia_sp.1
---

```{r setup, include=F}
library(tidyverse)
library(cmdstanr)
library(bayesplot)
```

```{r fit}
print(params$species)

fit <- list()
tryCatch({
  chain_path <- file.path("Chains", "Hybrid", params$species)
  fit <- as_cmdstan_fit(list.files(chain_path,
                                   full.names = TRUE))},
  error=function(e){cat("ERROR :",params$species, conditionMessage(e), "\n")}
)
# names(fit)

```

```{r chains}
fit$draws(c("alpha", "beta1", "beta2_p", "tau")) %>% 
  mcmc_trace()
```

```{r posteriors}
fit$draws(c("a", "O", "gamma", "tau")) %>% 
  mcmc_dens()
```

```{r predictions}
DATA <- fit$summary("p") # p posterior

# prediction environment 
DATA <- DATA %>% 
  rowwise() %>% 
  mutate(Light = as.numeric(unlist(str_extract_all(variable, "\\d+"))[1])) %>% 
  mutate(Topo = as.numeric(unlist(str_extract_all(variable, "\\d+"))[2])) %>% 
  mutate(logTransmittance = seq(-7.308724e+00, 8.941571e-08, length.out = 100)[Light]) %>% # -7.308724e+00 , 8.941571e-08
  mutate(logTWI = seq(1.358045, 2.400176, length.out = 100)[Topo]) %>% # 1.358045 - 2.400176
  mutate(Transmittance = round(exp(logTransmittance), 3)) %>%
  mutate(TWI = exp(logTWI))

```

```{r}
DATA %>% 
  group_by(Topo) %>% 
  # At light optimum (i.e. O median)
  filter(abs(logTransmittance-fit$summary("O")$median) == min(abs(logTransmittance-fit$summary("O")$median))) %>% 
  ggplot(aes(x = TWI)) +
  theme_minimal() +
  geom_point(aes(y = median), size=0.7) + # p posterior median
  geom_ribbon(aes(ymin = q5, ymax = q95), color = 'red', alpha = 0.2) + # P quantiles
  ggtitle("At light optimum") +
  ylab("Presence probabiblity median")
```

```{r}
DATA %>% 
  group_by(Light) %>% 
  # At topo optimum (i.e. presence proba. max)
  filter(median==max(median)) %>% 
  ggplot(aes(x = logTransmittance)) +
  theme_minimal() +
  geom_point(aes(y = median), size=0.7) + # p posterior median
  geom_ribbon(aes(ymin = q5, ymax = q95), color = 'red', alpha = 0.2) + # P quantiles
  geom_vline(xintercept  = fit$summary("O")$median, color = "#00AFBB", linewidth=1) + # Opt median
  geom_vline(xintercept  = fit$summary("O")$q5, linetype="dashed") + # Opt Q5%
  geom_vline(xintercept  = fit$summary("O")$q95, linetype="dashed") + # Opt Q95%
  # scale_x_continuous(trans="log") +
  ggtitle("At logTWI optimum") +
  ylab("Presence probabiblity median")
```

# Heatmap
```{r}
library(viridis)
ggplot(DATA, aes(x=TWI, y=logTransmittance, fill = median)) + 
  theme_minimal() +
  geom_tile() + # heatmap
  scale_x_continuous(trans="log") +
  scale_fill_viridis(name="Presence probabiblity")
```

```{r}
# Proba to be in the light across logTWI
ggplot(DATA, aes(x=TWI, y= median, col= Transmittance)) +
  theme_minimal() +
  geom_point() +
  scale_color_viridis() +
    scale_x_continuous(trans="log") +
  ylab("Presence probabiblity median")


ggplot(DATA, aes(x= logTransmittance, y= median, col= TWI)) +
  theme_minimal() +
  geom_point() +
  scale_color_viridis(direction = -1) +
  ylab("Presence probabiblity median")


# Optimum move
# ggplot(DATA, aes(x=logTWI, y= fit$summary("O")$median)) +
#   geom_point() 

```

# 3D
https://www.sthda.com/english/wiki/impressive-package-for-3d-and-4d-graph-r-software-and-data-visualization
```{r}
library(viridis)

lattice::wireframe(median ~ logTWI + logTransmittance,
                   data = DATA,
                   zlab = list("Presence prob.", rot=90),
                   zlim = c(min(DATA$median), max(DATA$median)),
                   drape = TRUE, col.regions = viridis(100), scales = list(arrows = F),  
                   main='Light x topography niche', xlab='logTWI', ylab='logTransmittance',
                   par.settings = list(axis.line = list(col = 'transparent')),
                   screen=list(z = -120, x = -70, y = 3)) # z = 120, x = -70, y = 3

# 3D fixe
plot3D::scatter3D(x = DATA$logTWI, y = DATA$logTransmittance, z = DATA$median, colvar = DATA$median,
                  clab = "Presence probability",
                  main = params$species, xlab = "logTWI",
                  ylab ="logTransmittance", zlab = "Presence probability",
                  ticktype = "detailed", pch = 20, cex = 3, # pch = 20 : petit rond plein, cex : la taille du point
                  col = viridis(100), colkey = F,
                  theta = 130, phi = 20,  bty = "g")

# 3D pivotable : 
plotly::plot_ly(DATA, x = ~logTWI, y = ~logTransmittance, z = ~median, color = ~median)
```

