---
params:
title: "Compute MEM on observations"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---

MEM: Moran’s eigenvector maps

```{r setup}
library(tidyverse)
library(cmdstanr)
library(spmoran)
```

# Load data
```{r Observations}
DATA <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/P16_2019_Paracou_InvandEnv.csv")

CoordXY <- DATA %>% select(Xutm, Yutm) # %>% unique() # dataframe with x and y coordinates in columns
```

```{r Compute MEM}
# approximated spatial eigenvectors
# minimum spanning tree connecting sample sites (exp( -d(i,j)/h))
Sys.time() 
MEM <- meigen_f(CoordXY, model = "exp", enum = 200)
Sys.time() # 8s
# MEM$sf
# sf : Matrix of the spatial eigenvectors (N x L)
# ev : Vector of the spatial eigenvalues (L x 1), scaled to have the maximum value of 1

```

# Save the eignevectors
```{r}
eigenval <- as.data.frame(MEM$sf) # n rows = n obs, n col = n eigenvectors
write_csv(eigenval, "D:/Mes Donnees/PhD/Inventories/Data/Agregation/Eigenvectors/All_obs_Eigenvectors_25ha.csv")

# for glmnet (MEM of the observations, covariables and prediction
# dataall <- DATA %>% 
#   bind_cols(eigenval) %>% 
#   select(-variable)
# 
# write_csv(dataall, paste0("D:/Mes Donnees/PhD/Inventories/Data/Agregation/Eigenvectors/dataall_", sp, ".csv"))
# }
```

# 9ha
```{r}
rm(eigenval)
CoordXY_25ha <- CoordXY
```

## Load data
```{r Observations}
DATA <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/P16_2019_Paracou_InvandEnv.csv") %>% 
  filter(SubPlot %in% c(13,14,15,18,19,20,23,24,25)) # 40928

CoordXY <- DATA %>% select(Xutm, Yutm) # %>% unique() # dataframe with x and y coordinates in columns

ggplot(CoordXY_25ha, aes(Xutm, Yutm)) +
  geom_point() +
  geom_point(data=CoordXY, col ="red")
```

## Compute the eigenvectors
```{r Compute MEM}
# approximated spatial eigenvectors
# minimum spanning tree connecting sample sites (exp( -d(i,j)/h))
Sys.time() 
MEM <- meigen_f(CoordXY, model = "exp", enum = 200)
Sys.time() # 5s
# MEM$sf
# sf : Matrix of the spatial eigenvectors (N x L)
# ev : Vector of the spatial eigenvalues (L x 1), scaled to have the maximum value of 1

```

## Save the eigenvectors
```{r}
eigenval <- as.data.frame(MEM$sf) # n rows = n obs, n col = n eigenvectors
write_csv(eigenval, "D:/Mes Donnees/PhD/Inventories/Data/Agregation/Eigenvectors/All_obs_Eigenvectors_9ha.csv")
```
