---
title: "Check Cirad trees position"
author: "Vincyane"
date: "`r Sys.Date()`"
output: html_document
---
We need :
- Xutm, Yutm coordinates
- Guyafor.nb (= field number of trees bigger than 10cm DBH given by Guyafor Protocol)

# Packages
```{r Setup, include = F}
library(readr)
library(tidyverse)
library(sf)
```

# Env data
```{r}
P16shp <- st_as_sf(terra::vect("D:/Mes Donnees/PhD/R_codes/PhD/test/Plot16.shp")) %>% 
  filter(SubPlot %in% c(13,14,15,18,19,20,23,24,25)) # ALT zone
```

```{r, include = F}
AdultsP16 <- read_csv("~/PhD/Inventories/Data/Adults/Paracou/2023-09-29_ParacouP16AllYears.csv") %>% # all P16 (25 ha)
  filter(CensusYear == 2020) %>% # last year
  # filter(SubPlot %in% c(13,14,15,18,19,20,23,24,25)) %>% # ALT zone
  filter(SubPlot %in% c(7,8,9,10,12,17,22, 13,14,15,18,19,20,23,24,25)) %>% # ALT zone and around
  # Only alive trees
  filter(CodeAlive == T) %>%
  filter(!is.na(TreeFieldNum) & !is.na(SubPlot) & !is.na(Xutm) & !is.na(Yutm)) %>%
  mutate(TreeFieldNum = as.character(TreeFieldNum)) %>% 
  unite(col = "Guyafor.nb", c("TreeFieldNum", "SubPlot"),
        sep = "_", na.rm = TRUE, remove = F) %>%
  # Scientific name
  mutate(Genus = ifelse(Genus=="Indet.MalvaceaeBombacoideae", 'Malvaceae-Bombacoideae', Genus)) %>% 
  unite(col = "ScientificName", c("Genus", "Species"),
        sep = "_", na.rm = TRUE, remove = F) %>% 
  # Circ to DBH
  mutate(Diameter = CircCorr/pi) %>% 
  select(Guyafor.nb, TreeFieldNum, SubPlot, ScientificName, Genus, Diameter, Xutm, Yutm) # Guyafor.nb, 

# AdultsPP <- read_csv("~/PhD/Inventories/Data/Adults/NouraguesPetitPlateau_2022.csv")
```

```{r,include = F, message=F}
Understory <- 
  # read_csv("~/PhD/Inventories/Data/Understory/Paracou/ALT_Paracou_9ha_CLEAN.csv") %>% 
  read_csv("~/PhD/Inventories/Data/Understory/Paracou/ALT_Paracou9ha_20250129.csv") %>% # last raw data
  rename(Xutm = XTreeUTM, Yutm = YTreeUTM) %>%
  rename(DBH = Diameter) %>%
  separate(col = "Guyafor.nb", sep = "_", into = c("TreeFieldNum", "SubPlot"), remove = F) %>% 
  # filter(Stem.nb == 1) %>% 
  filter(!is.na(Guyafor.nb)) %>% # only cirad trees
  filter(!is.na(Xutm) & !is.na(Yutm)) %>% # coordonnées relatives au quadrat
  
  mutate(ScientificName = ifelse(ScientificName=="Annona_amboty", "Annona_ambotay", ScientificName)) %>%
  mutate(Species = ifelse(Species=="amboty"& Genus=="Annona", "ambotay", Species)) %>%
  mutate(Family = ifelse(Family=="Lecithidaceae", "Lecythidaceae", Family)) %>%
  mutate(Genus = ifelse(Genus=="Lecithidaceae", "Lecythidaceae", Genus)) %>%
  mutate(ScientificName = str_replace(ScientificName, "Lecithidaceae", "Lecythidaceae")) %>%
  
  select(IdTree, Guyafor.nb, TreeFieldNum, SubPlot, IdStem, Subplot, Stem.nb, ScientificName, Genus, Species, DBH, Xutm, Yutm, Comments)

range(na.omit(Understory$DBH)) # 1 196.0 ya des arbres dits cirad <10 alors que ce sont les tiges principales
length(unique((Understory %>% 
                 filter(is.na(ScientificName)))$Guyafor.nb)) # 221 arbres cirad sans identification bota
```

# Compute coordinates difference (euclidian distance)
```{r}
options(scipen = 999)

all <- Understory %>% 
  filter(Stem.nb == 1) %>%
  # left_join(AdultsP16, by = "TreeFieldNum", suffix = c("U","A")) %>% 
  left_join(AdultsP16, by = "Guyafor.nb", suffix = c("U","A")) %>%
  mutate(Dist = sqrt((XutmU - XutmA)^2 + (YutmU - YutmA)^2)) %>% # Compute coordinates difference (euclidian distance)
  # Homogenise bota names
  
  mutate(ScientificNameA = str_replace(ScientificNameA, "_Indet.", "_sp")) %>%
  mutate(ScientificNameU = str_replace(ScientificNameU, "_indet", "_sp")) %>%
  
  mutate(ScientificNameA = str_remove(ScientificNameA, "Indet.")) %>% 
  mutate(GenusA = str_remove(GenusA, "Indet.")) %>% 
  mutate(ScientificNameU = str_remove(ScientificNameU, "Indet.")) %>% 
  mutate(GenusU = str_remove(GenusU, "Indet.")) %>% 
  
  mutate(ScientificNameU = str_remove(ScientificNameU, "-CAY")) %>% 
  mutate(ScientificNameU = str_remove(ScientificNameU, "Guyafor")) %>% 
  mutate(ScientificNameU = sub("\\..*", "", ScientificNameU)) %>% # after the dot
  mutate(ScientificNameA = sub("\\..*", "", ScientificNameA)) %>% 
  mutate(ScientificNameU = gsub("[[:digit:]]", "", ScientificNameU)) %>% # the digit
  mutate(ScientificNameU = gsub("FG-Holst", "", ScientificNameU)) %>% 
  # mutate(ScientificNameU = gsub("\\.", "", ScientificNameU)) %>%
  
  mutate(ScientificNameA = str_remove(ScientificNameA, "_subsp")) %>%
  mutate(ScientificNameU = str_remove(ScientificNameU, "Indet")) %>% 
  mutate(GenusU = str_remove(GenusU, "Indet.")) %>% 
  mutate(ScientificNameA = ifelse(ScientificNameA=="Indet", NA, ScientificNameA)) %>%
  mutate(GenusA = ifelse(GenusA=="Indet.", NA, GenusA)) %>% 
  
  # Compute DBH difference
  mutate(DBHdiff = DBH - Diameter)

length(unique(all$Guyafor.nb)) == nrow(all)
length(unique(all$IdTree)) == nrow(all)

length(unique((all %>% 
                 filter(is.na(GenusA)))$IdTree)) # 479 arbres sans nom de genre

```

# Check unique combinaison between IdTree, IdStem and Guyafor.nb 
```{r}
library(data.table)
setDT(all)
if(!"Comment" %in% names(all)) all[, Comment := ""]

for (i in c("IdStem", "Guyafor.nb")) {
  
  duplicated_ID <- CorresIDs <- vector("character") # empty vector
  
  CoordIDCombination <- na.omit(unique(
    all[, .(IdTree, get(i))]
  ))
  
  CorresIDs <- CoordIDCombination[, V2] # .(IdTree) 
  
  if(!identical(CorresIDs, unique(CorresIDs))){ # check if it's the same length, same ids -> 1 asso/ID
    
    duplicated_ID <- unique(CorresIDs[duplicated(CorresIDs)]) # identify the Idtree(s) having several combinations
    
    
    all[get(i) %in% duplicated_ID, 
        Comment := paste0(Comment, "Non-unique combinaison of IdTree and ",i, sep ="/")]
    
    
    warning(paste("Non-unique combinaison of IdTree and ",i))
    
  } else message("Unique IdTree-",i,"associations")
  
}

# write.csv(all, "~/PhD/Inventories/Data/Understory/Paracou/Problems/Cirad_trees_positions_diff_ALTvsGuyafor.csv")
```

```{r}
length(all$Comment[grepl("Non-unique combinaison of IdTree", all$Comment)])/nrow(all)*100 # 0.3% of cirad trees

all[grepl("Non-unique combinaison of IdTree", all$Comment)]

length(unique((all[grepl("Non-unique combinaison of IdTree and Guyafor.nb", all$Comment)])$IdTree)) # 12 trees
```
```{r}
# Botanical name diff
nrow(all %>% filter(ScientificNameA != ScientificNameU)) # 41
nrow(all %>% filter(GenusA != GenusU)) # 26

botacheck <- all %>% filter(ScientificNameA != ScientificNameU) %>%
  select(ScientificNameA,ScientificNameU,GenusA,GenusU, Species, Dist, DBHdiff)
Genuscheck <- all %>% filter(GenusA != GenusU) %>%
  select(ScientificNameA,ScientificNameU,GenusA,GenusU, Species, Dist, DBHdiff)

nrow(all %>% 
       filter(grepl("Non-unique combinaison of IdTree and Guyafor.nb", Comment)) %>%
       filter(ScientificNameA != ScientificNameU)) # 2


# Coordinates diff
range(all$Dist, na.rm = T) # 0.01875 114.30519 !

nrow(all %>% filter(Dist>5)) # 190

loin <- all %>% filter(Dist>5)%>%
  select(ScientificNameA,ScientificNameU,GenusA,GenusU, Species, Dist, DBHdiff)


nrow(all %>% 
       filter(grepl("Non-unique combinaison of IdTree and Guyafor.nb", Comment)) %>% 
       filter(Dist>2)) # 6

# DBH diff
range(all$DBHdiff, na.rm = T) # -94.53381 178.01549 !

nrow(all %>% filter(DBHdiff > 15 | DBHdiff <(- 2))) # 56 arbres

growthpb <- all %>% filter(DBHdiff > 15 | DBHdiff <(- 2))%>%
  select(ScientificNameA,ScientificNameU,GenusA,GenusU, Species, Dist, DBHdiff)


nrow(all %>% filter(grepl("Non-unique combinaison of IdTree and Guyafor.nb", Comment)) %>% filter(DBHdiff > 15 | DBHdiff <(- 2))) # 0 arbres

# Together
nrow( all %>% 
        filter(ScientificNameA != ScientificNameU) %>% 
        filter(Dist>2) %>% # 15
        filter(DBHdiff > 15 | DBHdiff <(- 2)) ) # 0

```

# Check in other Subplots
```{r}
test <- all %>% 
  group_by(IdTree) %>% 
  # Same species name
  mutate(SelectedSp = ifelse(GenusA==GenusU | is.na(GenusA==GenusU), T, F)) %>% 
  mutate(NbSelectedSp = sum(SelectedSp, na.rm = T)) %>%  # combien de T par Guyafor.nb
  # Closer coordinates
  group_by(IdTree, SelectedSp) %>% 
  mutate(SelectedCoord = ifelse(SelectedSp & Dist== min(abs(Dist)), T, F)) %>% 
  ungroup() %>% group_by(IdTree) %>% 
  mutate(NbSelectedCoord = sum(SelectedCoord)) %>% # combien de T par Guyafor.nb
  ungroup()

# Checks
## Combien de matchs
match <- test %>% 
  filter(SelectedCoord==T) # 4355/4485

## Combien sans match (pcq pas bonne sp)
test %>% 
  filter(NbSelectedSp==0) %>% select(IdTree) %>% unique() # 26


## Dans les matchs, quelle range dist, quelle range de diff de DBH
range(match$Dist) # 0.01875 114.30519 !
range(match$DBHdiff, na.rm = T) # -94.53381 178.01549 !
## Dans les matchs, combien de changement de subplot, quelle range dist, quelle range de diff de DBH
testchange <- test %>%
  filter(SelectedCoord & SubPlotU!=SubPlotA) # 0
length(unique(testchange$IdTree)) # 71
range(testchange$Dist) #  0.5579328 361.9058622 !
range(testchange$DBHdiff, na.rm = T) # -36.28733  39.28028

## Quest-ce qu'il ya de satisfaisant :
OK <- test %>% 
  filter(SelectedCoord==T & Dist<5 & GenusA==GenusU & (DBHdiff < 15 & DBHdiff >(- 2)))  # 3743/4485 -> 83%
range(OK$DBHdiff, na.rm = T) #  -5.797791 13.701407
OKchange <- OK %>%
  filter(SelectedCoord & SubPlotU!=SubPlotA) # 0 parmis les ok ont changé de plot

# Combien étaient mal identifiés
badbota <- test %>%
  filter(GenusA!=GenusU & SubPlotU==SubPlotA) %>% select(IdTree) %>% unique() # 26 

# Combien étaient très loin
loin <- test %>%
  filter(Dist>10 & SubPlotU==SubPlotA) %>% select(IdTree) %>% unique() # 79 (- ce qui ont été mis dans un autre subplot)

# Combien avient des taux de croissance aberrants
growthpb <- test %>%
  filter(SubPlotU==SubPlotA & (DBHdiff > 15 | DBHdiff <(- 2))) %>% select(IdTree) %>% unique() # 56 

# Combien sont encore mal identifiés
badbota <- test %>%
  filter(SelectedCoord==T & GenusA!=GenusU) %>% select(IdTree) %>% unique() # 0 

# Combien sont encore très loin
loin <- test %>%
  filter(SelectedCoord==T & Dist>10) %>% select(IdTree) %>% unique() # 77 

# Combien ont encore des taux de croissance aberrants
growthpb <- test %>%
  filter(SelectedCoord==T & (DBHdiff > 15 | DBHdiff <(- 2))) %>% select(IdTree) %>% unique() # 56 

test0 <- test %>% 
  filter(NbSelectedCoord==0) # 26/4485 arbres cirad n’ont pas un bon match
length(unique(test0$IdTree)) 

test0sp <- test %>% 
  filter(NbSelectedSp==0) #%>% # 26 arbres sans aucun match de nom de genre entre ALT et Guyafor...sans compter les NA
length(unique(test0sp$IdTree)) 

testsup <- test %>% 
  filter(NbSelectedCoord>1) # 0 -> 1 seul match final youhou! 
testsup <- test %>% 
  group_by(IdTree) %>% 
  filter(NbSelectedCoord>1) # 0 -> 1 seul match final youhou! 

checkchange <- test %>%
  filter(IdTree %in% testchange$IdTree) # 0

testgrand <- test %>%
  filter(SelectedCoord & DBHdiff >15) # 17 arbres qui ont grandit vachement vite en 3 ans
length(unique(testgrand$IdTree))
range(testgrand$DBHdiff) # 15.02253 178.01549
range(testgrand$Dist) # 0.05303301  2.66866218

testloin <- test %>%
  filter(SelectedCoord & Dist >3) # 613 qui commencent à etre loin..
length(unique(testloin$IdTree))
range(testloin$Dist) #  3.0000 114.3052
range(testloin$DBHdiff, na.rm = T) # -35.33236  11.75672

test %>% filter(SelectedCoord) %>%
  ggplot(aes(x=Dist))+
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
  # scale_x_continuous(limits = c(0, 90), breaks = seq(0, 90,by=2)) +
  # scale_y_continuous(limits = c(0, 1050), breaks = seq(0, 1050,by=50))+
  labs(x= "Coordinates differences (distance (m))")
```

```{r, eval=F}
test <- all %>% 
  filter(grepl("Non-unique combinaison", Comment)) %>% # 128/4 537 arbres
  filter(Dist>2) %>% # 79
  filter(DBH>20) # 64

write.csv(test, "~/PhD/Inventories/Data/Understory/Paracou/Problems/Nonunique_combinaison_IdTree-Guyafornb.csv")

test <- all %>% 
  filter(grepl("Non-unique combinaison", Comment)) %>% 
  # filter(ScientificNameA != ScientificNameU) %>%   # 25/4 537 arbres
  filter(DBHdiff > 15 | DBHdiff <(- 2)) # 0 arbres


test <- all %>% 
  filter(grepl("Non-unique combinaison", Comment)) %>% 
  filter(ScientificNameA == ScientificNameU)  # 94/4 537 arbres
# filter(ScientificNameA!="Indet") %>%   
# filter(DBHdiff > 15 | DBHdiff <(- 2)) # 0 arbres


test <- all %>% 
  filter(Dist>2) %>%   # 1 660/4 537 arbres
  filter(!grepl("Non-unique combinaison", Comment)) # 1581/4 537 arbres


test <- all %>% 
  # filter(DBH < Diameter) %>% 
  mutate(DBHdiff = DBH - Diameter) %>%
  filter(DBHdiff > 15 | DBHdiff <(- 2)) # 85/4 537 arbres

test <- all %>% 
  filter(Dist>2) %>%   
  filter(!grepl("Non-unique combinaison", Comment)) %>% 
  mutate(ScientificNameU = str_remove(ScientificNameU, "Indet")) %>% 
  filter(ScientificNameA != ScientificNameU) %>%  # 98/4 537 arbres
  # filter(ScientificNameA!="Indet") %>%   
  filter(DBHdiff > 15 | DBHdiff <(- 2)) # 0 arbres



unique(test$ScientificNameA)
(test %>% filter(Guyafor.nb =="320_20"))$ScientificNameU
```

# Plot
```{r, eval=F}
# cols <- rainbow(100, s=.6)[sample(1:100,100)] # , v=.9

test %>% 
  filter(SelectedCoord) %>% 
  filter(Dist>90) %>%
  # filter(!grepl("Non-unique combinaison", Comment)) %>% # si on ne veut que si sont cohérents idtree-guyafor.nb
  ggplot() +
  geom_sf(data = sf::st_cast(P16shp, "LINESTRING")) +
  geom_point(aes(XutmU, YutmU, col= Guyafor.nb, shape = "ALT"), size = 2) +
  geom_point(aes(XutmA, YutmA, col= Guyafor.nb, shape = "Cirad"), size = 2) +
  scale_shape_manual(values = c("ALT" = 17, # pour donner un nom à chaque intitulé
                                "Cirad" = 15)) # pour ordonner

ggsave("CiradTrees_ALTvsGuyafor_Distsup15_afterExplo.png", path="D:/Mes Donnees/PhD/Figures/inventory/",
       width = 25, height = 20, units = "cm", dpi=800, bg="white")
# ils sont sur les bords des carrés -> ALT et Guyafor n’ont pas exactement les même limites de subplot -> ils ne sont pas considérés dans le même subplot dans ALT et Guyafor...


all %>% 
  # filter(Dist>25) %>% 
  ggplot(aes(x=Dist))+
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
  labs(x= "Coordinates differences (distance (m))")
```

