
```{r}
PATH <- "//amap-data.cirad.fr/work/users/VincyaneBadouard/Modelisation/Plots/Light_topo_onto/Autocor"
fits <- readRDS(paste(PATH, "/fits.rds", sep=''))

Envpred <- read_csv("D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/Realdata/Envrmt_prediction_25ha.csv") %>% 
  mutate(DBH_classes = recode(DBH_classes, "-25" = ">25")) %>% 
  rename(DBH = DBH_classes)
```

# Prepare data
- applique l’équation avec a et O médian et mettre gamma à 0
- pas de la barre de O, sans incertitude
- citer en discussion pour se référer aux espèces et dans résultats
```{r}
Sys.time()

d <- list()
p <- list()

# S= "Oxandra_asbeckii" 
# D="1-3"


for(S in names(fits)){
  plist[[S]] <- local({
  for(D in c("1-3","3-10","10-25",">25")){
    if(D %in% names(fits[[S]])){
      
      d[[S]][[D]] <- fits[[S]][[D]]$summary(c("O","a"), median) %>% # , "tau"
        pivot_wider(names_from = variable,
                    values_from = median) 
      
      p[[S]][[D]] <- Envpred %>% 
        select(-Topographyp) %>% 
        filter(DBH==D) %>% 
        mutate(P = rstanarm::invlogit(d[[S]][[D]]$a*(Lightp - d[[S]][[D]]$O)^2)) %>%  #  + tau*Topographyp
        mutate(Sg_effect = ifelse(d[[S]][[D]]$a > -0.02, F, T)) # -0.02
      
    }
  }
      DATA <- list_rbind(list_flatten(p)) %>% 
        mutate(Species = S) %>% 
      mutate(DBH = factor(DBH, levels=c("1-3","3-10","10-25",">25")))
      
      DATA %>% 
      ggplot(aes(col = DBH)) +
      theme_minimal() +
      geom_line(aes(x = Lightp, y = P, linetype = Sg_effect), size=0.7) + # p median
      scale_linetype_manual(values = c('TRUE' = "solid",
                                       'FALSE' = "dashed")) +
      
      scale_color_manual(values = c("1-3" = "#00AFBB",
                                    "3-10"= "#CC79A7",
                                    "10-25"= "#E7B800",
                                    ">25" = "#FC4E07"),
                         breaks=c("1-3","3-10","10-25",">25")) + 
      
      scale_fill_manual(values = c("1-3" = "#00AFBB",
                                   "3-10"= "#CC79A7",
                                   "10-25"= "#E7B800",
                                   ">25" = "#FC4E07"),
                        breaks=c("1-3","3-10","10-25",">25")) + 
      
      scale_x_continuous(name = "Light (% transmittance)",
                         n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
      ggtitle(str_replace(S, "_", " ")) +
      labs(y="Presence probabiblity median", col='DBH (cm)', fill='DBH (cm)')
    
  })
}


plots <- gridExtra::marrangeGrob(plist, nrow = 3, ncol = 3) # 70
# plots

ggsave("Allsp_Light_niche_atTWIoptimum_stages_gamma0.pdf",
       path = PATH,
       plots, width = 15, height = 10)

Sys.time() # 4 min

```
Topographyp : 1 valeur par espèce et pas stade : topo la plus représentée par l'sp à cette taille
comme gamma change juste la hauteur de la courbe



# Plots
```{r predictions}
Sys.time()

datalist <- list()
Olist <- list()
alist <- list()
plist <- list()

for(s in names(fits)){
  plist[[s]] <- local({
    # s= "Lecythis_persistens"
    for(d in c("1-3","3-10","10-25",">25")){
      # d= ">25"
      if(d %in% names(fits[[s]])){
        
        datalist[[d]] <- fits[[s]][[d]]$summary("p") %>%  # p posterior
          # prediction environment 
          rowwise() %>% 
          mutate(DBH = d) %>% 
          mutate(Light = as.numeric(unlist(str_extract_all(variable, "\\d+"))[1])) %>% 
          # mutate(Topo = as.numeric(unlist(str_extract_all(variable, "\\d+"))[2])) %>% 
          mutate(logTransmittance = Envpred[Envpred$DBH_classes==d,]$Lightp[Light]) 
        # mutate(logTWI = Envpred[Envpred$DBH_classes==d,]$Topographyp[Topo])
        
        Olist[[d]] <- data.frame(
          DBH = d,
          O = fits[[s]][[d]]$summary("O", median)$median,
          fits[[s]][[d]]$summary("O",
                                 quantiles = ~ quantile2(., probs = c(0.2, 0.8)))
          # OQ5 = fits[[s]][[d]]$summary("O")$q5, # Opt Q5%
          # OQ95 =fits[[s]][[d]]$summary("O")$q95
        )
        alist[[d]] <- data.frame(
          DBH = d,
          a = fits[[s]][[d]]$summary("a", median)$median
        )
        
      }
    }
    DATA <- list_rbind(list_flatten(datalist)) %>% 
      mutate(DBH = factor(DBH, levels=c("1-3","3-10","10-25",">25")))
    
    aDATA <- list_rbind(list_flatten(alist)) %>% 
      mutate(DBH = factor(DBH, levels=c("1-3","3-10","10-25",">25")))
    
    # ODATA <- list_rbind(list_flatten(Olist)) %>% 
    #   mutate(DBH = factor(DBH, levels=c("1-3","3-10","10-25",">25")))
    
    DATA <-  DATA %>% 
      left_join(aDATA, by="DBH") %>% 
      left_join(ODATA, by="DBH") %>% 
      mutate(Incertitude = q20-q80) %>% 
      mutate(Sg_effect = ifelse(a > -0.02 | Incertitude > 5, F, T)) # -0.02
    
    
    
    DATA %>% 
      ggplot(aes(col = DBH, fill=DBH)) +
      theme_minimal() +
      geom_line(aes(x = logTransmittance, y = median, linetype = Sg_effect), size=0.7) + # p posterior median
      scale_linetype_manual(values = c('TRUE' = "solid",
                                       'FALSE' = "dashed")) +
      
      # geom_ribbon(aes(x = logTransmittance, ymin = q5, ymax = q95),
      #             alpha = .1, col=NA, linewidth=0.5) + # P quantiles
      # geom_vline(data = ODATA, aes(xintercept  = O, col= DBH), linewidth=0.8) + # Opt median
      
      # geom_rect(data = ODATA, aes(xmin = q20, xmax = q80, # O quantiles
      #                             ymin=0, ymax=Inf), fill=NA, linetype="dotted") +
      
      # geom_vline(data = ODATA, aes(xintercept  = OQ5, col= DBH),  linetype="dashed") + # Opt Q5%
      # geom_vline(data = ODATA, aes(xintercept  = OQ95, col= DBH),  linetype="dashed") + # Opt Q95%
      scale_color_manual(values = c("1-3" = "#00AFBB",
                                    "3-10"= "#CC79A7",
                                    "10-25"= "#E7B800",
                                    ">25" = "#FC4E07"),
                         breaks=c("1-3","3-10","10-25",">25")) + 
      
      scale_fill_manual(values = c("1-3" = "#00AFBB",
                                   "3-10"= "#CC79A7",
                                   "10-25"= "#E7B800",
                                   ">25" = "#FC4E07"),
                        breaks=c("1-3","3-10","10-25",">25")) + 
      
      scale_x_continuous(name = "Light (% transmittance)",
                         n.breaks = 10, labels = ~round(exp(.)*100,2)) + # delog
      ggtitle(paste(str_replace(s, "_", " "),"- at logTWI optimum")) +
      labs(y="Presence probabiblity median", col='DBH (cm)', fill='DBH (cm)')
    
  })
}


plots <- gridExtra::marrangeGrob(plist, nrow = 3, ncol = 3) # 70
# plots

# ggsave("Allsp_Light_niche_atTWIoptimum_stages_gamma0.pdf",
#        path = PATH,
#        plots, width = 15, height = 10)

Sys.time() # 4 min
```

