---
title: "Sampling"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---

# Species
```{r setup}
library(tidyverse)
library(cmdstanr)
library(foreach) # parallisation
library(parallel)

# sp <- (read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,2]) # 75

sp <- "Tabernaemontana_macrocalyx" #"Pogonophora_schomburgkiana"

```

# Presence data
```{r data}
path <- "D:/Mes Donnees/PhD/R_codes/PhD/Modelisation/"

# load real presence-absences data on 25ha 
load(paste(path, "Realdata/Realsp_25ha.Rdata", sep=''))
# View(datalist[[1]])

datalist <- datalist[names(datalist) %in% sp] # only species in sp
# View(datalist[["Iryanthera_hostmannii"]])
```

# DataM
```{r, dataM}
Np <- 50 # number of predictions
N_D_p = 5 # n DBH


# les noms des var doivent etre les memes que dans le fichier stan
dataM <- lapply(datalist, function(x) list(N = nrow(x), # 47 850
                                           Presence = x$Presence,
                                           Light = x$logTransmittance,
                                           Topography = x$logTWI,
                                           DBH = x$logDBH,
                                           # number of predictions
                                           N_L_p = Np, # light
                                           N_T_p = Np, # topography
                                           N_D_p = N_D_p, # DBH
                                           # environment of predictions
                                           Lightp = seq(min(x$logTransmittance), max(x$logTransmittance), length.out = Np),
                                           # Topographyp = seq(min(x$logTWI), max(x$logTWI), length.out = Np),
                                           Topographyp = median(x[x$Presence==1,]$logTWI), # la topographie la plus représentée
                                           DBHp = log(c(2.5, 7.5, 15, 25, 35)))
)
# median(datalist[[1]][datalist[[1]]$Presence==1,]$TWI)
# hist(datalist[[1]][datalist[[1]]$Presence==1,]$TWI)
# median(datalist[[1]][datalist[[1]]$Presence==1,]$logTWI)
# seq(min(datalist[[1]]$logTWI), max(datalist[[1]]$logTWI), length.out = Np) # 1.358045 - 2.400176
# seq(min(datalist[[1]]$logTransmittance), max(datalist[[1]]$logTransmittance), length.out = Np) # -7.308724e+00 , 8.941571e-08

names(dataM) <- names(datalist)
```

# Model
```{r model}
Sys.time()
model_name <- "Hybrid"
model <- cmdstan_model(
  file.path(
    "Model",
    paste0(model_name, ".stan")
  ))
Sys.time() # 1 min
```

# Sampling
```{r, eval=F}
Sys.time()

chain_path <- file.path("Chains", model_name, sp)
if(!file.exists(chain_path)){
  # unlink(chain_path, recursive = TRUE)
  dir.create(chain_path)
  fit <- model$sample(data = dataM[[sp]],
                      chains = 4,
                      parallel_chains = 4,
                      save_warmup = FALSE)
  fit$save_output_files(dir = chain_path)
}
Sys.time() # 30-45 min 1 sp
```

```{r sampling}
Sys.time()

gc()
# parallel::detectCores() # 8
cores = min(c(length(dataM), 2)) # nbr of cores to use, 8/4 per model -> 2 max
i <- NULL
j = length(dataM)

# L'enregistrement des clusters
cl <- parallel::makeCluster(cores, outfile = "")
doSNOW::registerDoSNOW(cl)

# Progress bar:
# pb <- txtProgressBar(min = 0, max = j, style = 3)
pb <- txtProgressBar(max=j)
# progress <- function(n) setTxtProgressBar(pb, n)
progress <- function(n) cat(sprintf("Run %d is complete\n", n))
opts <- list(progress = progress)

foreach::foreach(
  i=1:j,
  .packages = c("cmdstanr"), # necessary packages
  .options.snow = opts # ProgressBar
) %dopar% {
  
  chain_path <- file.path("Chains", model_name, sp[i])
  if(!file.exists(chain_path)){
    # unlink(chain_path, recursive = TRUE)
    dir.create(chain_path)
    fit <- model$sample(data = dataM[[sp[i]]],
                        chains = 4,
                        parallel_chains = 4,
                        save_warmup = FALSE)
    fit$save_output_files(dir = chain_path)
  }
}

# close progressbar and cluster
close(pb)
stopCluster(cl)
Sys.time() # 16h
```


```{r}

```

