---
title: "Trajectories plot"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---
pas de couleur mais ajouter wetter, drier
```{r setup}
library(tidyverse)
library(viridis)
library(posterior)
library(factoextra)
library(grid)
library(patchwork)

PATH <- "//amap-data.cirad.fr/work/users/VincyaneBadouard/Modelisation/Plots/Light_topo_onto/Autocor"

posteriors <- read_csv(paste(PATH, "/Posteriors.csv", sep =''))
muche <- read_csv(paste(PATH, "/Light_ontogenic_trajectories.csv", sep =''))
Summary <- read_csv(paste(PATH,'/Trajectories_summary_allsp_5-14.csv',sep='')) %>% 
  select(Categories, N, `%`) %>% 
  unique()

```

```{r}
# Summary$Categories
lev <- c("shade-light", "shade", "shade-intermediate",
         "intermediate-light", "intermediate-shade-light", "light-shade-light",
         "light-shade","generalist", "generalist-intermediate")

Q80 <- posteriors %>% 
  filter(variable =="O")

datap <- muche %>% 
  mutate(`O_>25` = as.character(`O_>25`)) %>% 
  pivot_longer(cols = starts_with("O_"),
               values_to = "O") %>% 
  mutate(DBH = str_remove(name, "O_")) %>% 
  select(-name) %>% 
  left_join(Q80, by = c("Species", "DBH")) %>% 
  mutate(DBH = factor(DBH, levels=c("1-3","3-10","10-25",">25"))) %>% 
  select(Species, Categories, Trajectories, DBH, O) %>% 
  left_join(Summary, by ='Categories') %>% 
  mutate(Categories = factor(Categories, levels = lev)) %>% 
  arrange(Categories) %>% 
  mutate(Species = str_replace(Species, "_", " "))

```

```{r}
muche %>% 
  select(Species, Categories, Trajectories, SameDirection) %>% 
  filter(Categories=="shade-light") %>% 
  filter(SameDirection=="not all in the same direction")
```

# With smooth
```{r}
plist <- list()
# C = 'shade-light'
for(C in unique(datap$Categories)){
  if(!grepl("generalist", C)){
    if(unique((datap %>% filter(Categories==C))$N)>1){
      
      plist[[C]] <- local({
        
        # print(
        dataC <- datap %>% 
          filter(Categories==C) %>% 
          mutate(O = as.numeric(O))
        ggplot(dataC, aes(x = DBH, y = O)) +
          theme_minimal() +
          # geom_segment(aes(y=ll, yend=hh, x=DBH, xend=DBH), size = 0.2, linetype = 'dashed') +
          # geom_segment(aes(y=l, yend=h, x=DBH, xend=DBH), size = 1, linetype = 'dashed') +
          # geom_point() +
          geom_line(aes(group=Species), linewidth=0.5, col= "grey") + 
          geom_smooth(aes(x = as.numeric(DBH), y = O), col = "black", span= 1.5, se=F) +
          # geom_smooth(aes(x = as.numeric(DBH), y = O, col = Categories), span= 1.5, se=F) +
          # scale_color_manual(values = c("shade-light" = "#f1c232",
          #                               "shade" = "#5c40a6",
          #                               "shade-intermediate" = "#fc4e07",
          #                               "intermediate-light" = "#bf9000",
          #                               "intermediate-shade-light" = "#d00069",
          #                               "light-shade-light" = "#00afbb",
          #                               "light-shade" = "#009e73")) +
          
          scale_y_continuous(name = "Light (% transmittance)",
                             limits = c(min(as.numeric(datap$O), na.rm = T),0),
                             n.breaks = 10, labels = ~round(exp(.)*100,2)) +
          labs(title=paste(C, ' (',round(unique(dataC$`%`)),'%)', sep=""), x= 'DBH (cm)') +
          theme(axis.title=element_blank(), plot.title.position = "plot") +
          coord_flip() +
          guides(color = F)
        
        # )
      })
    }
  }
  
}

# plots <- gridExtra::marrangeGrob(plist, nrow = 3, ncol = 3) # 
# # plots
# 
# ggsave("Trajectories_nonflat_smooth_bigcategories.pdf",
#        path = PATH,
#        plots, width = 15, height = 10)
```
## Rares
```{r}
# plist[['rare']] <- local({
#   
#   # print(
#   rares <- datap %>% 
#     filter(N==1) %>% 
#     filter(!grepl("generalist", Categories)) %>% 
#     mutate(O = as.numeric(O))
#   ggplot(rares, aes(x = DBH, y = O)) +
#     theme_minimal() +
#     geom_line(aes(group=Species), linewidth=0.5, col= "grey") + 
#     geom_smooth(aes(x = as.numeric(DBH), y = O), span= 1.5, col = 'red', se=F) +
#     scale_y_continuous(name = "Light (% transmittance)",
#                        limits = c(min(as.numeric(datap$O), na.rm = T),0),
#                        n.breaks = 10, labels = ~round(exp(.)*100,2)) +
#     labs(title=paste(paste(unique(rares$Categories), collapse="/"),
#                      ' (',round(sum(rares$`%`[c(1,nrow(rares))])),'%)', sep=''), x= 'DBH (cm)') +
#     theme(axis.title=element_blank(), plot.title.position = "plot") +
#     coord_flip()
# })

```

```{r}
# plots <- gridExtra::marrangeGrob(plist, nrow = 3, ncol = 3)
# 
# ggsave("Trajectories_nonflat_smooth_bigcategories_flip.pdf",
#        path = PATH,
# plots, width = 15, height = 10)


multiplots <- ggpubr::ggarrange(plotlist = plist, nrow = 3, ncol = 3)
# ggpubr::annotate_figure(multiplots, left = textGrob("Light (% transmittance)", rot = 90, vjust = .5, gp = gpar(cex = 1.3)),
#                         bottom = textGrob("DBH (cm)", gp = gpar(cex = 1.3)))
ggpubr::annotate_figure(multiplots, left = textGrob("DBH (cm)", rot = 90, vjust = .5, gp = gpar(cex = 1.3)),
                        bottom = textGrob("Light (% transmittance)", gp = gpar(cex = 1.3)))


ggsave("Trajectories_nonflat_smooth_bigcategories_flip.png", # _col
       path = PATH,
       width = 23, height = 15, units = "cm", dpi=800, bg="white")

```

## Flats
```{r}
# C="intermediate-generalist-light"
plist <- list()

data_flat <- datap %>% 
  filter(O!="NA") %>% 
  mutate(O = ifelse(O!="flat", as.character(round(exp(as.numeric(O))*100,2)), O))

for(C in unique(datap$Categories)){
  if(grepl("generalist", C)){
    plist[[C]] <- local({
      
      data_C <- data_flat %>% 
        filter(Categories==C)
      
      # print(
      data_C %>% 
        mutate(O = factor(O, levels = unique(data_C$O))) %>% 
        
        ggplot(aes(x = DBH, y = O, col=Species, group=Species)) +
        theme_minimal() +
        geom_point() +
        geom_line() +
        # scale_y_discrete(name = "Light (% transmittance)",
        # limits = c("0","100")) +
        # breaks = labels(data_flat$O)) + # [seq(1, length(levels(data_flat$O)), by = 2)]
        labs(title=C, x= 'DBH (cm)', y= 'Light (% transmittance)')
      
      # )
    })
  }
  
}

plots <- gridExtra::marrangeGrob(plist, nrow = 2, ncol = 2) # 75
# plots

# ggsave("Trajectories_withflat.pdf",
#        path = PATH,
#        plots, width = 15, height = 10)

```

# With species in colors
## Divide shade-light (in 3)
```{r}
marge <- -10
plist <- list()

for(C in unique((datap %>% filter(Categories=="shade-light"))$Trajectories)){
  if(!grepl("generalist", C)){
    if(unique((datap %>% filter(Trajectories==C))$N)>1){ 
      
      plist[[C]] <- local({
        
        # print(
        dataC <- datap %>% 
          filter(Trajectories==C) %>% 
          mutate(O = as.numeric(O))
        ggplot(dataC, aes(x = DBH, y = O, group=Species, col=Species)) +
          theme_minimal() +
          # geom_segment(aes(y=ll, yend=hh, x=DBH, xend=DBH), size = 0.2, linetype = 'dashed') +
          # geom_segment(aes(y=l, yend=h, x=DBH, xend=DBH), size = 1, linetype = 'dashed') +
          # geom_point() +
          geom_line() + 
          scale_y_continuous(name = "Light (% transmittance)",
                             limits = c(min(as.numeric(datap$O), na.rm = T),0),
                             n.breaks = 10, labels = ~round(exp(.)*100,2)) +
          labs(title=C, x= 'DBH (cm)') +
          # {if(C == 'shade-light') guides(col= guide_legend(ncol = 2)) } +
          theme(axis.title=element_blank(), plot.title.position = "plot",
                legend.margin=margin(0,0,0,0),
                legend.box.margin=margin(marge,marge,marge,marge)) +
          coord_flip()
        
        # )
      })
    }
  }
}

```

```{r}
for(C in unique(datap$Categories)[-1]){
  if(!grepl("generalist", C)){
    if(unique((datap %>% filter(Categories==C))$N)>1){ # mettre les raw cat pour diviser shade-light
      
      plist[[C]] <- local({
        
        # print(
        dataC <- datap %>% 
          filter(Categories==C) %>% 
          mutate(O = as.numeric(O))
        ggplot(dataC, aes(x = DBH, y = O, group=Species, col=Species)) +
          theme_minimal() +
          # geom_segment(aes(y=ll, yend=hh, x=DBH, xend=DBH), size = 0.2, linetype = 'dashed') +
          # geom_segment(aes(y=l, yend=h, x=DBH, xend=DBH), size = 1, linetype = 'dashed') +
          # geom_point() +
          geom_line() + 
          scale_y_continuous(name = "Light (% transmittance)",
                             limits = c(min(as.numeric(datap$O), na.rm = T),0),
                             n.breaks = 10, labels = ~round(exp(.)*100,2)) +
          labs(title=paste(C, ' (',round(unique(dataC$`%`)),'%)', sep=""), x= 'DBH (cm)') +
          # {if(C == 'shade-light') guides(col= guide_legend(ncol = 2)) } +
          theme(axis.title=element_blank(), plot.title.position = "plot",
                legend.margin=margin(0,0,0,0),
                legend.box.margin=margin(marge,marge,marge,marge)) +
          coord_flip()
        
        # )
      })
    }
  }
  
}
```


## Rares
```{r}
# plist[['rare']] <- local({
#   
#   # print(
#   rares <- datap %>% 
#     filter(N==1) %>% 
#     filter(!grepl("generalist", Categories)) %>% 
#     mutate(O = as.numeric(O))
#   ggplot(rares, aes(x = DBH, y = O, group=Species, col=Species)) +
#     theme_minimal() +
#     geom_line() + 
#     scale_y_continuous(name = "Light (% transmittance)",
#                        limits = c(min(as.numeric(datap$O), na.rm = T),0),
#                        n.breaks = 10, labels = ~round(exp(.)*100,2)) +
#     labs(title=paste(paste(unique(rares$Categories), collapse="/"),
#                      ' (',round(sum(rares$`%`[c(1,nrow(rares))])),'%)', sep=''), x= 'DBH (cm)') +
#     theme(axis.title=element_blank(), plot.title.position = "plot",
#           legend.margin=margin(0,0,0,0),
#           legend.box.margin=margin(marge,marge,marge,marge)) +
#     coord_flip()
# })

```

```{r}
# plots <- gridExtra::marrangeGrob(plist, nrow = 2, ncol = 2)
# 
# ggsave("Trajectories_nonflat_species_bigcategories_flip.pdf",
#        path = PATH,
#        plots, width = 15, height = 10)
```

```{r}

plist[[1]] | (plist[[2]] / plist[[3]])
ggsave("Trajectories_nonflat_species_bigcategories_flip_shade-light.png",
       path = PATH,
       width = 23, height = 15, units = "cm", dpi=800, bg="white")

(plist[[4]] | plist[[5]]) / (plist[[6]] | plist[[7]]) 
ggsave("Trajectories_nonflat_species_bigcategories_flip_01.png",
       path = PATH,
       width = 23, height = 15, units = "cm", dpi=800, bg="white")

(plist[[8]] | plist[[9]])
ggsave("Trajectories_nonflat_species_bigcategories_flip_02.png",
       path = PATH,
       width = 23, height = 15, units = "cm", dpi=800, bg="white")

```

# Stature vs trajectories
```{r}
H_allometry <- read_csv('D:/Mes Donnees/PhD/Inventories/Data/Height-Diameter/H_allometry_method.csv')

Stature <- read_csv("D:/Mes Donnees/PhD/Inventories/Data/Adults_Understory/Paracou/P16_2019_Paracou_InvandEnv.csv") %>% 
  filter(SubPlot %in% c(13,14,15,18,19,20,23,24,25)) %>% 
  # select(ScientificName, TreeHeight)
  group_by(ScientificName) %>% 
  summarise(TreeHeightQ95 = quantile(TreeHeight, 0.95, na.rm=T),
            DBHQ95 = quantile(DBHcor, 0.95, na.rm=T)) %>%
  ungroup() %>% 
  left_join(H_allometry, by='ScientificName') %>% 
  mutate(Species = str_replace(ScientificName, "_", " "))

datapp <- datap %>% left_join(Stature, by='Species') %>% 
  select(Species, Categories, TreeHeightQ95, DBHQ95) %>% 
  unique() %>% 
  mutate(Categories = factor(Categories,
                             levels = c("generalist", 'shade', "light-shade",
                                        "shade-intermediate", "generalist-intermediate", 
                                        "intermediate-shade-light", "shade-light",
                                        "intermediate-light","light-shade-light"))) %>% 
  group_by(Categories) %>% 
  mutate(N = n()) %>% 
  ungroup() %>% 
  filter(N>1)
```

```{r}
label <- datapp %>% 
  group_by(Categories) %>% 
  summarise(N = paste("N: ", n()))

ggplot(datapp, aes(x=Categories, y=TreeHeightQ95)) + 
  theme_minimal() + 
  geom_boxplot() +
  # stat_summary(fun = "length", hjust = 0.5, vjust = 0.9) +
  geom_text(data = label, aes(label = N, x= Categories),
            y = Inf, vjust = 1.5, show.legend = F) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(y= "Species Q95% tree height (m)", x= 'Species temperament trajectories accros ontogeny') +
  theme(legend.position="bottom")

ggsave("TreeHeightQ95_vs_trajectories.png", path = PATH,
       width = 14, height = 10, units = "cm", dpi=800, bg="white")
```

# Trajectories vs DBH
```{r}
datapp %>% 
  group_by(Categories) %>% 
  summarise(DBHmax = max(DBHQ95))
```

```{r}
ggplot(datapp, aes(x=Categories, y=DBHQ95)) + 
  theme_minimal() + 
  geom_boxplot() +
  # stat_summary(fun = "length", hjust = 0.5, vjust = 0.9) +
  geom_text(data = label, aes(label = N, x= Categories),
            y = Inf, vjust = 1.5, show.legend = F) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(y= "Species DBH (cm)", x= 'Species temperament trajectories accros ontogeny') +
  theme(legend.position="bottom")

# 
# ggsave("DBHQ95_vs_trajectories.png", path = PATH,
#        width = 14, height = 10, units = "cm", dpi=800, bg="white")
```

