---
title: "Compute MNT, TWI, relative elevation and Hillshade"
author: "Sylvain"
date: "2023-08-07"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  message = FALSE, echo = FALSE, fig.width = 6
)
```

```{r setup, include=FALSE}
library(tidyverse)
library(terra)
library(lidR)
library(foreach)
library(tidyterra)
library(sf)

knitr::opts_chunk$set(echo = TRUE)
```

[code example](https://github.com/sylvainschmitt/PhD/blob/master/documents/preliminary/environment/TopoDerivate.sh)

# DEM from LAS

1. LAZ > MNT on-by-one

```{r, eval=FALSE}
las_path = "D:/Mes Donnees/PhD/Lidar/ALS2022/Paracou/las"
mnt_path = "D:/Mes Donnees/PhD/Lidar/ALS2022/Paracou/MNT"

lases <- list.files(las_path)

las_to_dem <- function(las_file, las_path, mnt_path) {
  name <- gsub(".laz", "", las_file) # name of the file
  lidR::readLAS(file.path(las_path, las_file)) %>% 
    
    lidR::rasterize_terrain(algorithm = lidR::tin()) %>% # to mnt
    
    terra::writeRaster(file.path(mnt_path, paste0(name, ".tif")), overwrite=TRUE) # write the mnt in .tif
  # print(name, "is done.\n")
}

# lapply(lases, las_to_dem, las_path = las_path,
#        mnt_path = mnt_path)
```

```{r}
cores = 2
j = length(lases)

# l'enregistrement des clusters
cl <- parallel::makeCluster(cores)
doSNOW::registerDoSNOW(cl)

output <- foreach::foreach(
  i=1:j,
  .packages = c("magrittr") #, .options.snow = opts
) %dopar% {
  print(i)
  las_to_dem(lases[i], 
             las_path = las_path,
             mnt_path = mnt_path)
}

# close the cluster
stopCluster(cl)
```

```{r}
# las <- readLAS("input/Paracou_284500_581500.laz")
# dem <- rasterize_terrain(las, algorithm = tin())
# 
# dems <- list.files('input', full.names = T) %>% 
#   lapply(readLAS) %>% 
#   lapply(rasterize_terrain, algorithm = tin())
# 
# dem <- do.call(terra::merge, dems)
# 
# writeRaster(dem, "output/dem.tif")
```

2. Merge MNTs
```{r, eval=FALSE}
dems <- list.files(mnt_path, full.names = TRUE) %>% 
  lapply(terra::rast)
dem <- do.call(terra::merge, dems)
writeRaster(dem, "D:/Mes Donnees/PhD/Lidar/ALS2022/Paracou/MNT/Paracou_MNT.tif")
```

3. View DEM
```{r}
Paracou <- sf::st_read("D:/Mes Donnees/PhD/SIG_data/Plots Paracou/OverallPlots.shp")

mnt <- terra::rast("D:/Mes Donnees/PhD/Lidar/ALS2022/Paracou/MNT/Paracou_MNT_cor.tif")
res(mnt) # 1

terra::plot(mnt)
plot(Paracou, add=T)

ggplot() + 
  geom_spatraster(data = mnt, aes(fill = Z)) +
  scale_fill_gradientn(name = "Elevation (m)",
                       colors = terrain.colors(45, rev=T)) + 
  geom_sf(data = sf::st_cast(Paracou, "LINESTRING")) +
  ggtitle("Paracou MNT ALS 2022") + 
  coord_sf()
```

```{r}
# Different resolution 
# 5m for TWI
mnt5m <- aggregate(mnt, fact=5)

res(mnt5m) # 5

ggplot() + 
  geom_spatraster(data = mnt5m, aes(fill = Z)) +
  scale_fill_gradientn(name = "Elevation (m)",
                       colors = terrain.colors(45, rev=T)) + 
  geom_sf(data = sf::st_cast(Paracou, "LINESTRING")) +
  ggtitle("Paracou MNT ALS 2022 - 5m resolution") + 
  coord_sf()

writeRaster(mnt5m, "D:/Mes Donnees/PhD/Lidar/ALS2022/Paracou/MNT/Paracou_MNT_5m.tif", overwrite=TRUE)
writeRaster(mnt5m, "D:/Mes Donnees/PhD/R_codes/PhD/test/Paracou_MNT_5m.tif", overwrite=TRUE)
```

# TWI
in bash commands

`cd`: change directory command
`var=`: define a variable
`$var`: call the value of the variable

```{bash, eval=FALSE}
cd "/d/Mes Donnees/PhD/R_codes/PhD"
saga="/d/Program/SAGA/saga_cmd.exe" # chemin executable
dem="test/Paracou_MNT_5m.tif" # dans le meme dossier que cd
twi="test/Paracou_TWI_5m.srgd" # dans le meme dossier que cd
$saga ta_hydrology 15 -DEM $dem -TWI $twi # commande

# " ta_hydrology 15" :  module
# " -DEM " : dem filled
# dem : chemin
# " -TWI " : sortie
# twi : chemin
```
translate in .tif
```{r, eval=FALSE}
TWI <- terra::rast("test/Paracou_TWI_5m.sdat")  # sdat données du fichier TWI au format SAGA 

terra::writeRaster(TWI, "test/Paracou_TWI_5m.tif", overwrite=TRUE)
```
plot
```{r}
terra::rast("test/Paracou_MNT_cor.tif") %>% 
  terra::plot()
terra::rast("test/Paracou_TWI_5m.tif") %>% 
  terra::plot()
```
```{r}
ggplot() + 
  geom_spatraster(data = TWI, aes(fill = Paracou_TWI_5m)) +
  scale_fill_gradientn(name = "TWI",
                       colors =  hcl.colors(12, "Blues", rev = T)) + 
  geom_sf(data = sf::st_cast(Paracou, "LINESTRING")) +
  ggtitle("Paracou TWI 5 m ALS 2022") + 
  coord_sf()
```

# Relative Elevation

https://gis.stackexchange.com/questions/154172/saga-tool-relative-heights-and-slope-positions-what-do-results-tell-me

```{bash, eval=FALSE}
cd "/d/Mes Donnees/PhD/R_codes/PhD"
saga="/d/Program/SAGA/saga_cmd.exe"
dem="test/Paracou_MNT_cor.tif"
re="test/re.srgd"
$saga ta_morphometry 14 -DEM $dem -SH $re
```
translate in .tif
```{r, eval=FALSE}
RE <- terra::rast("test/re.sdat") # sdat données du fichier RE au format SAGA
terra::writeRaster(RE, "test/re.tif", overwrite=TRUE)
```
plot
```{r}
ggplot() + 
  geom_spatraster(data = RE, aes(fill = re)) +
  scale_fill_gradientn(name = "Relative elevation to the creek (m)",
                       colors = hcl.colors(45, "Blues")) +
  geom_sf(data = sf::st_cast(Paracou, "LINESTRING")) +
  ggtitle("Paracou Relative elevation to the creek - ALS 2022") + 
  coord_sf()
```
# Hillshade

```{bash, eval=FALSE}
cd "/d/Mes Donnees/PhD/R_codes/PhD"
saga="/d/Program/SAGA/saga_cmd.exe"
dem="test/Paracou_MNT_cor.tif"
hs="test/hs.srgd"
$saga ta_lighting 0 -ELEVATION $dem -SHADE $hs
```
translate in .tif
```{r, eval=FALSE}
Hillshade <- terra::rast("test/hs.sdat") # sdat données du fichier HS au format SAGA
terra::writeRaster(Hillshade, "test/hs.tif", overwrite=TRUE)
```
plot
```{r}
ggplot() + 
  geom_spatraster(data = Hillshade, aes(fill = hs)) +
  scale_fill_gradientn(name = "Hillshade",
                       colors = hcl.colors(2, "Grays", rev=T)) +
  geom_sf(data = sf::st_cast(Paracou, "LINESTRING")) +
  ggtitle("Paracou Hillshade - ALS 2022") + 
  coord_sf()
```

# For P16
## Plot 16 geometry
```{r}
shpGuyafor <- raster::shapefile("D:/Mes Donnees/PhD/SIG_data/Guyafor/GuyaforSubPlots.shp")

shpParacou <- shpGuyafor[shpGuyafor@data$Forest == "Paracou",]
plot(shpParacou, col = shpParacou@data$Plot == "16")

Plot16 <- shpParacou[shpParacou@data$Plot == "16",] %>% 
  st_as_sf()
plot(Plot16)
```

# Clip for just the plot 16
```{r}
source("~/PhD/R_codes/PhD/LiDAR_scripts/Functions/Clip_raster.R")

P16_mnt <- Rslt <- Clip_raster(file_to_clip = "test/Paracou_MNT_cor.tif",
                               mask = Plot16, 
                               outpout = "test/Paracou_P16_MNT.tif")


P16_TWI <- Clip_raster(file_to_clip = "test/Paracou_TWI_5m.tif",
                       mask = Plot16, 
                       outpout = "test/Paracou_P16_TWI_5m.tif")

P16_RE <- Clip_raster(file_to_clip = "test/re.tif",
                      mask = Plot16, 
                      outpout = "test/Paracou_P16_RelativeElev.tif")
```

## Plot the P16 rasters
```{r}
# MNT
ggplot() + 
  geom_spatraster(data = P16_mnt, aes(fill = Z)) +
  scale_fill_gradientn(name = "Elevation (m)",
                       colors = terrain.colors(30, rev=T),
                       na.value="white") +
  geom_sf(data = sf::st_cast(Plot16, "LINESTRING")) +
  ggtitle("Paracou P16: MNT - ALS 2022") +
  theme_classic() +
  coord_sf()

# TWI
ggplot() + 
  geom_spatraster(data = P16_TWI, aes(fill = Paracou_TWI_5m)) +
  scale_fill_gradientn(name = "TWI",
                       colors =  hcl.colors(9, "Blues", rev = T),
                       na.value="white") + 
  geom_sf(data = sf::st_cast(Plot16, "LINESTRING")) +
  ggtitle("Paracou P16: TWI 5 m - ALS 2022") + 
  theme_classic() +
  coord_sf()

# Relative elevation
ggplot() + 
  geom_spatraster(data = P16_RE, aes(fill = re)) +
  scale_fill_gradientn(name = "Relative elevation to the creek (m)",
                       colors = hcl.colors(25, "Blues"),
                       na.value="white") +
  geom_sf(data = sf::st_cast(Plot16, "LINESTRING")) +
  ggtitle("Paracou P16: Relative elevation to the creek - ALS 2022") + 
  theme_classic() +
  coord_sf()
```

# For ALT zone
## ALT zone geometry
```{r}
ALT <- shpParacou[shpParacou@data$Plot == "16" & shpParacou@data$SubPlot %in% c("13","14","15","18","19","20", "23","24","25"),]
plot(ALT)
```


