---
title: "DBH distributions by species"
author: "Vincyane Badouard"
date: "`r Sys.Date()`"
output: pdf_document
---

# Packages
```{r Setup, include = F}
library(tidyverse)
library(data.table)
library(ggforce)
```

# Import cleaned inventory data
```{r,include = F, message=F}
Understory <- read_csv("~/PhD/Inventories/Data/Understory/Paracou/ALT_Paracou_9ha_CLEAN.csv")
```


# Plot
```{r}
# All
ggplot(Understory, aes(x=DBH)) +
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9)
```

# Plot per species
ne prendre que :
- les identifiés botaniquement
- la tige principale (?)
- les vivants
- les mesures les plus récentes des arbres cirad 
```{r}
sort(unique(Understory$ScientificName))

data <- Understory %>%
  filter(Genus=="Xylopia"|Genus=="Parkia"| Genus=="Ocotea")


ggplot(data, aes(x=DBH)) +
  geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) +
  facet_wrap(vars(ScientificName, N, Strategy), scales = "free") +
  labs(x ="DBH (cm)", y = "Number of individuals")
```

```{r}
sp <- Understory$ScientificName

# Define nrow and ncol for the facet
n <- length(unique(sp))
if(n<4) {i = 1}else{ i = 4}


pdf("DBH_distributions_by_species.pdf", width = 15, height = 10)
for(p in 1:(ceiling(length(unique(sp))/16))){
  print(
    ggplot(Understory, aes(x=DBH)) +
      geom_histogram(binwidth=1, fill="#69b3a2", color="#e9ecef", alpha=0.9) + # color to have the lines of the bars
      
      ggforce::facet_wrap_paginate(vars(ScientificName, N, Strategy),
                                   scales = "free",
                                   ncol = min(n,4), nrow = i, page = p) +
      
      labs(x ="DBH (cm)", y = "Number of individuals")
    
  )
}
dev.off() # Close the final graphics device
```


