---
title: "Retreive plots of CanopyConstructor data"
author: "Vincyane"
date: "`r Sys.Date()`"
output: html_document
---

# Packages
```{r Setup, include = F}
library(tidyverse)
library(data.table)
library(readr)
library(BIOMASS)
```

# Import CanopyConstructor data
```{r,include = F, message=F}

filenames <- list.files("~/PhD/Inventories/Data/Height-Diameter/CanopyConstructor-P1to16_00006_0010/", full.names=TRUE) # catch the name of all the files of the folder

df_list <- lapply(filenames, read_delim, delim = "\t",
                  escape_double = FALSE, trim_ws = TRUE) # read all the folder files

CC <- do.call(rbind, df_list)
unique(CC$paramID)
```

# Import P16 data
```{r}
P16 <- EcoFoG::Guyafor2df(UID = "Vincyane.Badouard", PWD = "Vincyane973+", Driver = "SQL Server",WHERE="Forest='Paracou' AND Plot='16'") %>% 
  select(idTree, Plot) %>% unique()
```

# Filter P16 CC data
```{r}
test <- CC %>% 
  rename(idTree = id) %>% 
  left_join(P16, by="idTree") %>% 
  filter(!is.na(Plot)) %>% 
  group_by(idTree) %>% 
  mutate(Height = mean(height)) %>% # simulations average
  mutate(CrownRadius = mean(CR)) %>% # CrownRadius ?
  ungroup() %>% 
  rename(DBH = dbh) %>% 
  mutate(DBH = DBH*100) %>%  # in cm
  select(idTree, DBH, Height, CrownRadius) %>% unique()

nrow(CC);nrow(test) # 69315

length(unique(test$idTree)) # 13863*5 = 69315
```

```{r}
write.csv(test, "~/PhD/Inventories/Data/Height-Diameter/CanopyConstructorDataP16.csv")
```

