---
title: "Theorical_coordinates_P16"
author: "Vincyane"
date: "`r Sys.Date()`"
output: html_document
---
P16 : 25 ha
Coordonnées SO de la P16: (0;0)

```{r}
library(tidyverse)
library(sf)
library(terra)
```

# Subplots grid for 25 ha
```{r}
grid <- data.frame(expand.grid(
  x = seq(0,500, by= 100),
  y = seq(0,500, by= 100)
)
)
ggplot() +
  geom_point(data=grid, aes(x = x, y = y)) + # il faut mettre l'argument data sinon ça ne marche pas
  coord_fixed(ratio=1) # same axis size
```
# ALT stakes grid
```{r}
ALT <- data.frame(expand.grid(
  x = seq(0,500, by= 10),
  y = seq(0,500, by= 10)
)
)
ggplot() +
  geom_point(data=ALT, aes(x = x, y = y)) + # il faut mettre l'argument data sinon ça ne marche pas
  coord_fixed(ratio=1) # same axis size
```

# LAI200 sensors theorical coordinates
- transect HOBO : 20 points espacés de *10m* : start =(390;110)  ; end = (390;300)
- transect layon : 26 points espacés de *2m* : start = (350;200) ; end = (400; 200)
```{r}
LAI2200_HOBO <- data.frame(
  Sensor = "LAI2200",
  Transect = "HOBO",
  Id = as.character(seq(1:20)), # S->N
  x = 390,
  y = seq(110,300, by= 10)
)
nrow(LAI2200_HOBO)==20

LAI2200_LAY <- data.frame(
  Sensor = "LAI2200",
  Transect = "LAY",
  Id = as.character(rev(seq(1:26))), # E->O
  x = seq(350,400, by= 2),
  y = 200
)
nrow(LAI2200_LAY)==26

LAI2200 <- rbind(LAI2200_HOBO, LAI2200_LAY)

library(ggrepel)
ggplot() +
  geom_point(data=grid, aes(x = x, y = y)) + # il faut mettre l'argument data sinon ça ne marche pas
  geom_point(data=LAI2200_HOBO, aes(x = x, y = y), color = "red", size = 1)+
  geom_text_repel(data = LAI2200_HOBO, aes(x = x, y = y, label = Id), color = "black", size = 2) +
  geom_point(data=LAI2200_LAY, aes(x = x, y = y), color = "green", size = 0.3)+
  # geom_text_repel(data = LAI2200_LAY, aes(x = x, y = y, label = Id), color = "black", size = 2) +
  coord_fixed(ratio=1) # same axis size

```
# HOBO sensors theorical coordinates
- transect Jérome :
- transect BF :
- transect gap :
```{r}
# HOBO_jerome <-
# HOBO_BF <-
# HOBO_gap <-
```


# To UTM
P16 (x;y) :
NO	(285056;581678)
NE (285536;581821)
SE (285680; 581343)
SO (285201; 581199)

# Coordinates in UTM 
```{r}
data <- ALT # LAI2200 # grid

tab <- read_delim("D:/Mes Donnees/PhD/R_codes/PhD/local2UTM/CoordCoinsP1_16.csv", delim = ";", escape_double = FALSE, trim_ws = TRUE)

P=16 # Plot 16
limx = 500 # à changer pour la parcelle concernée
limy = 500 # à changer pour la parcelle concernée

dataUTM <- data %>% 
  mutate(Xutm = (1-x/limx)*(1-y/limy)*tab[P,]$`so x`+(x/limx)*(1-y/limy)*tab[P,]$`se x`+(y/limy)*(1-x/limx)*tab[P,]$`no x`+((x*y)/(limx*limy))*tab[P,]$`ne x`) %>% 
  mutate(Yutm = (1-x/limx)*(1-y/limy)*tab[P,]$`so y`+(x/limx)*(1-y/limy)*tab[P,]$`se y`+(y/limy)*(1-x/limx)*tab[P,]$`no y`+((x*y)/(limx*limy))*tab[P,]$`ne y`)

P16shp <- st_as_sf(vect("D:/Mes Donnees/PhD/R_codes/PhD/test/Plot16.shp"))
dataUTMsf <- st_as_sf(dataUTM, coords = c('Xutm','Yutm'))
dataUTMsf <- st_set_crs(dataUTMsf, crs(P16shp))

ggplot() +
  geom_sf(data = sf::st_cast(P16shp, "LINESTRING")) +
  geom_sf(data = dataUTMsf, col = "red", size = 0.3) +
  ggtitle("Paracou P16 - LAI2200 sensors positions")

# write.csv(LAI2200UTM, "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/LAI2200_theoretical_UTM.csv")
```

# Extract Z coord MNT to Points
```{r}
MNT <- terra::rast("//amap-data.cirad.fr/safe/lidar/ALS/Paracou/2023/rasters/PARACOU2023_DTM_1m.tif") # MNT
# "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/HighAltitudeFlight/dtm2023_4ha_HighAlt_buffer.asc"

crs(MNT) <- crs(P16shp)

plot(MNT) ; plot(dataUTMsf, add = T)

alt <- extract(MNT, dataUTMsf) %>% # extract z
  rename(Zutm = MNT_0.5m_IRD_500m_Paracou_284000_579500) %>% 
  select(-ID) %>% 
  mutate(Zutm = Zutm +1) # 1 m above the ground

dataxyz <- dataUTM %>% cbind(alt)

# write.csv(LAI2200UTMxyz, "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/LAI2200_theoretical_UTMxyz.csv")

generate_new_rows <- function(df) {
  new_rows <- data.frame()
  for (i in 1:nrow(df)) {
    new <- data.frame( # pour chaque x;y créer 59 incrémentations de Zutm
      x = df[i, "x"],
      y = df[i, "y"],
      Xutm = df[i, "Xutm"],
      Yutm = df[i, "Yutm"],
      Zutm = df[i, "Zutm"]:(df[i, "Zutm"] + 59)
    )
    new_rows <- rbind(new_rows, new)
  }
  return(new_rows)
}

dataxyz <- generate_new_rows(dataxyz)

# write.csv(dataxyz, "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/Grid10x10m_each1mZ_UTMxyz.csv")
```

# LAI2200 local positions (use VOP)
```{r}
path <- "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/Grid10x10m_each1mZ_UTMxyz.csv"
  # "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/LAI2200_theoretical_UTMxyz.csv"

dataxyz <- as.data.table(read.csv(path))
VOP <- as.matrix(read.table("//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/VOP_P16_9ha.txt"))

matrix <- as.matrix(dataxyz[, `:=`(c = 0 , d = 1)][,.(Xutm, Yutm, c, d)]) # as matrix of the same dimensions, without Z

datalocal <- matrix %*% t(VOP) # same dimensions

datalocal <- cbind(datalocal,dataxyz[,Zutm])[, -c(3,4)] # add Zutm

write.csv(datalocal, "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/Grid10x10m_each1mZ_local.csv")
# write.csv(LAI2200local, "//amap-data.cirad.fr/work/users/VincyaneBadouard/Lidar/ALS2023/LAI2200_theoretical_local.csv")
```

