---
title: "Diagnose all"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---

```{r setup}
library(tidyverse)
library(cmdstanr)
library(bayesplot)

# sp <- (read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,2]) # 75


# sp <- c("Licania_membranacea" , "Lecythis_persistens", "Piparea_multiflora",
#         "Iryanthera_hostmannii", "Tabernaemontana_macrocalyx") # 4 forms

sp <- "Symphonia_sp.1"

model_name <- "Affine" # Quadratic
```

```{r fits}
fits <- lapply(sp, function(s){
  chain_path <- file.path("Chains", model_name, s)
  fit <- as_cmdstan_fit(list.files(chain_path, full.names = TRUE)) # Read CmdStan CSV
})
names(fits) <- sp
```

ajouter en texte la médiane de beta1 et beta2 pour diagnostiquer le noeffect
```{r predictions}
g <- lapply(names(fits), function(f){
  
  fits[[f]]$summary("p") %>% # p posterior
    mutate(x = seq(5.7325, 23.61375, length.out = 100)) %>% # prediction environment
    ggplot(aes(x = x)) +
    geom_point(aes(y = median), size=0.7) + # p posterior median
    geom_ribbon(aes(ymin = q5, ymax = q95), color = 'red', alpha = 0.2) + # P quantiles
    # geom_vline(xintercept  = fits[[f]]$summary("O")$median, color = "#00AFBB", linewidth=1) + # Opt median
    # geom_vline(xintercept  = fits[[f]]$summary("O")$q5, linetype="dashed") + # Opt Q5%
    # geom_vline(xintercept  = fits[[f]]$summary("O")$q95, linetype="dashed") + # Opt Q95%
    ggtitle(gsub("_", " ", f)) +
    theme_minimal() +
    theme(axis.title = element_blank())
})

cowplot::plot_grid(plotlist = g)
```




