---
title: "Diagnose species"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
params:
  species: Licania_membranacea
---

```{r setup}
library(tidyverse)
library(cmdstanr)
library(bayesplot)

model_name <- c("Affine", "Quadratic")
```

```{r fit}
chain_path <- file.path("Chains", model_name, params$species)
fit <- as_cmdstan_fit(list.files(chain_path, full.names = TRUE))
```

```{r chains}
fit$draws(c("alpha", "beta1", "beta2")) %>% 
  mcmc_trace()
```

```{r posteriors}
fit$draws(c("alpha", "beta1", "beta2")) %>% 
  mcmc_dens()
```

```{r predictions}
fit$summary("p") %>% # p posterior
  # mutate(x = seq(-6, 0, length.out = n())) %>% # prediction environment
  ggplot(aes(x = x)) +
  theme_minimal() +
  geom_point(aes(y = median), size=0.7) + # p posterior median
  geom_ribbon(aes(ymin = q5, ymax = q95), color = 'red', alpha = 0.2) # P quantiles
# geom_vline(xintercept  = fits[[f]]$summary("O")$median, color = "#00AFBB", linewidth=1) + # Opt median
# geom_vline(xintercept  = fits[[f]]$summary("O")$q5, linetype="dashed") + # Opt Q5%
# geom_vline(xintercept  = fits[[f]]$summary("O")$q95, linetype="dashed") + # Opt Q95%
```




