---
title: "Sampling"
date: "`r Sys.Date()`"
format: html
self-contained: true
theme: cosmo
editor: source
code-fold: true
---

# Species
```{r setup}
library(tidyverse)
library(cmdstanr)
library(bayesplot)

sp <- (read.csv("D:/Mes Donnees/PhD/Inventories/Data/Understory/Paracou/InterestSpecies.csv")[,2]) # 75


# sp <- c("Licania_membranacea" , "Lecythis_persistens", "Piparea_multiflora",
#         "Iryanthera_hostmannii", "Tabernaemontana_macrocalyx") # 4 forms
# sp <- "Symphonia_sp.1"

model_name <- c("Affine", "Quadratic")
```

```{r fit}
fit <- list()
for(S in sp){
  for(M in model_name){
    chain_path <- file.path("Chains", M, S)
    fit[[S]][[M]] <- as_cmdstan_fit(list.files(chain_path, full.names = TRUE))
  }
}
# names(fit[["Symphonia_sp.1"]])
```


# Compute BIC for each species and each model
For each species and each model compute BIC and compare BIC for each species between models
Models with lower BIC are generally preferred
```{r BIC}
BIC <- list()

for(S in sp){
  for(M in model_name){

k <- length(fit[[S]][[M]]$metadata()$stan_variables[!fit[[S]][[M]]$metadata()$stan_variables %in% c("lp__", "p")]) # parameters nbr
N <- 47850 # observations nbr
L <- max(fit[[S]][[M]]$draws("lp__"))# the maximized value of the likelihood function of the model (fits[[f]]$summary("lp__"))

BIC[[S]][[M]] <- k*log(N) - 2*log(abs(L))

  }
}
```

# Compare BIC between models for each species
```{r}
for(S in sp){
  
  test <- BIC[[S]][["Affine"]] <= BIC[[S]][["Quadratic"]]
  
  if(test) print(paste(S, "- Lower BIC is for model: Affine:", round(BIC[[S]][["Affine"]], 1),"vs",round(BIC[[S]][["Quadratic"]], 1)))
  if(test==F) print(paste(S, " - Lower BIC is for model: Quadratic"))
  
}
```

